### ISSUE TITLE
Upgrade general Python dependencies

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1003]
Similar to bihealth/sodar-server#1453, should upgrade the overall dependencies for the next major release.

Especially should bump the minimum Django requirement to 3.2.15, as this fixes a high severity security issue.

## Tasks

- [x] Test upgrading `markdown`
- [x] Look into `django-autocomplete-light` upgrade issues (#1019)
- [x] Test upgrades with SODAR
- [x] Rerun versioneer

**Comment by mikkonie** [comment]
Done.
