### ISSUE TITLE
Update project list for flat layout and pagination

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1005]
**NOTE:** Rewriting an old issue to reflect current plans.

**NOTE 2:** Re-rewriting this in 2025-02 as I've thought of a much better design..

The project list should be updated to better support large amount of projects. With ~500 projects in SODAR, the list has since long ago grown unwieldy, despite optimizations in loading all the list data.

## Spec

- Display list GitLab-style as a flat list of category/project paths
    * No indent (obviously)
    * **TBD:** Highlight title of last category/project in path?
       + Makes sense but need to see how this looks in practice
   * **TBD:** Change into striped table?
       + Can be done now that list is no longer a tree
       + Will have to see how this looks like
- Attempt to optimize project list query
    * If this can be sufficiently optimized, we can still do the main query in one go and things become much simpler from here onwards..
    * Currenty we do several queries and also call `Project` model helpers after querying
    * Possible ways to optimize: `F` objects, caching data..
- IF optimizations fail, queries will have to be done per page
   * However, this would also be slow with the current implementation..
- Add pagination to list
    * Add default value for pagination (UI and/or Django setting)
    * Add user app setting override for user-specific default
- Idea: Use datatables to display list
    * This would remove the effort of implementing pagination ourselves
    * **Q:** Can we do custom filtering with "starred"?
    * **Q:** Can we still query for extra columns separately?
        + Probably yes, as datatables simply shows/hides HTML right?
- Query for extra column data only after project titles have been queried and displayed
    * Just like in the current implementation
- Ensure everything works under category
- Ensure everything works with long paths
    * Replace overflow container with wrap
- Hide role column for superuser
    * It's always the same role so this is redudnant
- Test with a large number of generated categories/projects in dev

## Tasks

- [x] Update `ProjectListAjaxView` to support flat list
- [x] Change layout into flat list
- [x] Optimize queries
- [x] Fix initial "N/A" value displayed in some categories
- [x] Update table layout for flat list
- [x] Enable displaying list with datatables
- [x] Add pagination to layout
- [x] Update filtering to use datatables filtering
- [x] Add custom datatables filtering for starred
- [x] Update pagination layout
- [x] Update additional column retrieval to work with datatables
- [x] Limit filter to title
- [x] Add optional highlight for project title
- [x] Update "message" feature to work with datatables
- [x] Add pagination Django setting
- [x] Add pagination control and user setting
- [x] Ensure layout works with long paths
- [x] Hide role column for superuser
- [x] Fix role column width in CSS
- [x] Ensure responsive modifications work for regular user and superuser
- [x] Fix `null` class in role column
- [x] Hide pagination controls with 1 page
- [x] Fix UI test waiting (see comments)
- [x] Try adjusting pagination CSS to match Django pagination template
- [x] Add/update tests
- [x] Update docs

**Comment by mikkonie** [comment]
With #1004 abandoned, this is not a critical feature at this point. Removing the milestone, but keeping the issue open for future implementation.

**Comment by mikkonie** [comment]
Postponing this to v1.1, as v1.0 is getting very bloated with critical breaking updates.

**Comment by mikkonie** [comment]
Updated with a completely rethought design.

**Comment by mikkonie** [comment]
Turns out there were some quite obvious points for optimizing the project list queries:

- `select_related()` missing from main query, which makes iterating through parent categories a pain
- `project_star` app setting queried separately for each project

**Comment by mikkonie** [comment]
Looks like certain UI tests may fail due to timing problems, should add the necessary waiting:

```
 ======================================================================
FAIL: test_project_list_custom_cols (projectroles.tests.test_ui.TestHomeView)
Test rendering custom columns
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/sodar-core/sodar-core/projectroles/tests/test_ui.py", line 821, in test_project_list_custom_cols
    self.assertEqual(c.get_attribute('innerHTML'), '0')
AssertionError: '<svg xmlns="http://www.w3.org/2000/svg" x[357 chars]svg>' != '0'
- <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24" class="iconify spin text-muted" data-icon="mdi:loading" style="vertical-align: -0.125em; transform: rotate(360deg);"><path fill="currentColor" d="M12 4V2A10 10 0 0 0 2 12h2a8 8 0 0 1 8-8"></path></svg>
+ 0
```

**Comment by mikkonie** [comment]
Done! That was a job and a half, but now we finally have a nice project list :)
