### ISSUE TITLE
Add displaying/hiding public guest access projects in project list

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1009]
I've been said it may be confusing for users to see publicly accessible projects on their project lists.

A simple way to avoid such confusion would be to add a control for displaying/hiding these projects, with the initial state being hidden UNLESS the user has direct roles to a public access project.

This should be done **after** #638 is merged, as the projectroles API use and project list populating will be altered.

Since we don't expect for a huge amount of public access projects, we can do this in a same way as we load starred projects: query for everything, display based on preference.

## Spec (WIP)

- Add a setting for displaying public access projects in projectroles
    * `name = list_public_projects`
    * `scope = USER`
    * `type = BOOLEAN`
    * `default = False`
    * `user_modifiable = True` (might as well also allow editing this in `userprofile`)
- Add button to project list header to display/hide public projects
- Add JQuery logic to button
    * **TODO**: Spec this
- Add tests
    * Tests for new setting
    * View & UI settings to ensure expected projects are returned and displayed when app setting value has changed
- Update projectroles docs on project list usage

## Tasks

- [ ] Add app setting
- [ ] Add display/hide button to template
- [ ] Add JQuery logic
- [ ] Add tests
- [ ] Update docs

**Comment by mikkonie** [comment]
It has been decided to abandon #1004 and go with an alternate implementation instead, which means this feature should definitely be implemented.

**Comment by mikkonie** [comment]
With the updated spec and prioritization for #1005, I believe this issue is no longer relevant. Instead, we might do a "show public projects" toggle similar to "starred", if there is demand for that. Closing this ticket for now.
