### ISSUE TITLE
Add project finder role

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1011]
We have been discussing the best ways to improve project discovery while maintaing access conrol. The approach earlier discussed in #1004 was abandoned in favor of the following design.

This feature requires #638 to be implemented.

## Spec

- Add a new user role level for project discovery
    * Name = `project finder`
    * Only allow setting this for categories (makes no sense for projects as they can not contain subprojects)
- Once user gets this role in a category, they can see the existence of all categories/projects under it
    * Requires full role inheritance (see #638)
    * Project titles will appear in project lists and searches
    * User does **not** get "guest" access to project data itself
- Allow finder user access to categories
    * This enables them to see users and can then request access
- Display project titles in project lists (also within categories), but do not enable links
    * Access to project views must naturally be denied
- Need ot make sure how `has_role()` is used in perms etc, as that may not be relevant anymore
    * Also need to mention this in breaking change docs!
- **TBD:** Behaviour in remote sync
    * Sync these to target sites or not?

## Tasks

- [x] Add migrations for role project type limiting and populating finder role
- [x] Add project type validation to `RoleAssignment`
- [x] Add finder role to existing rules and permissions
- [x] Add form UI functionality
- [x] Add project list functionality
- [x] Do not query for app columns for finder role in project list
- [x] Fix role column display for anonymous user in project list
- [x] Do not display role removal children warning for finder role
- [x] Update REST API project listing and retrieval for finder role
- [x] Update REST API role updating for finder role
- [x] Ensure expected behaviour in remote sync
- [x] Ensure category starring handling
- [x] Display findable projects in search results
- [x] Add icon and link to parent members in project list and search results
- [x] Update tests where needed
- [x] Update docs where needed

**Comment by holtgrewe** [comment]
I agree with all points.

Should we limit the assignment for the `project discovery` role in UI so it can only be assigned to categories?

We could add a button "info" to the project list that shows a modal with the project title, name/emails of owner and delegate(s).

**Comment by mikkonie** [comment]
Good question regarding the limitation to categories. I don't really see a reason to ever give "discoverable" access to a single user for a single project so yes, limiting it would be logical.

I'll think of a nice non-hardcoded way to include this limitation, as this might also be something we want to have for other future roles and e.g. when we implement role customization.

Also yes, having a simple link with a modal is most likely the nicest way to do this in the UI.

**Comment by mikkonie** [comment]
Done.
