### ISSUE TITLE
Refactor user signals

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1056]
While looking into this for bihealth/sodar-server#1315, I noticed some issues.

## Tasks

- [x] Refactor user name normalization into a reusable method
- [x] Remove redundant `User.save()` call
- [ ] Move signals to `signals.py`

**Comment by mikkonie** [comment]
Done.
