### ISSUE TITLE
Crash in get_app_icon_html() with missing project UUID in plugin entry point URL

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1057]
Reported by @stolpeo and currently occurring in Kiosc.

If a site app creates a timeline event linked to a project (which is not a common case but entirely acceptable), we get a crash in `get_app_icon_html()`. This is because the template tag assumes the plugin entry point URL to have a `project` kwarg without checking the plugin type.

## How to Reproduce

1. Create a `ProjectEvent` with a `project` foreign key and a site app as `app` (see example below)
2. Navigate to the details view (=Project Overview) or Timeline view of the project you refer to in the event
3. Observe the crash

Example for creating the event in `shell_plus`:

```
from projectroles.plugins import get_backend_api
timeline = get_backend_api('timeline_backend')
User = get_user_model()
p = Project.objects.filter(type='PROJECT').first()
e = timeline.add_event(project=p, app_name='example_site_app', user=User.objects.first(), event_name='test_event', description='Test', status_type='OK')
```

## Spec

- If `app != 'projectroles'`, check for plugin type in addition to presence of `ProjectEvent.project` before assigning the project UUID URL kwarg
    * If not `ProjectAppPlugin`, do not except the project UUID URL kwarg
- Just to be safe, add try-except to `reverse()`
    * Set URL to `None` if we get an exception

## Tasks

- [ ] Add plugin type check
- [ ] Add try-except to `reverse()`
- [ ] Add test(s) for event linked to a project created by a site app plugin

**Comment by gromdimon** [comment]
Seems to be done
