### ISSUE TITLE
User name for initial owner in project create form not following regular convention

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1059]
### Describe the Bug

When creating a project, the initial owner's name is not presented with the standard syntax of the user dropdown. Minor issue, but looks confusing.

### How to Reproduce

1. Navigate to a category under which you are able to create subcategories or projects
2. Click on "create project or category"
3. Observe the initial name in  the "owner" field

### Expected Behavior

This should be given in the same format provided by the dropdown when querying for choices: `Full Name (username) <email@example.com>`.

### Tasks

- [ ] Update initial value
- [ ] Assert the initial value in `projectroles.tests.test_views.TestProjectCreateView`

**Comment by mikkonie** [comment]
Starting points:

- The initial values for the widget are set in the following 4 lines: https://github.com/bihealth/sodar-core/blob/dev-0.11.1/projectroles/forms.py#L508
- The formatting of the user name is done here: https://github.com/bihealth/sodar-core/blob/dev-0.11.1/projectroles/views_ajax.py#L459

How to do this:

- Move the `get_result_label()` implementation under the `SODARUser` model as `get_form_label()`
    * Remember to add test(s) for this in `example_site.users.tests.test_models`
- Return `user.get_form_label()` in the existing `get_result_label()` method
    * This method must still be implemented for django-autocomplete-light, so don't remove it
- In `ProjectForm`, after setting `self.initial['owner']`, set the following:
    * `self.fields['owner'].label_from_instance = lambda x: x.get_form_label()`
    * You only need to call this once on line 512

**Comment by gromdimon** [comment]
Thank you very much for help!
I did:
- [x] `get_form_label()` method in `SODARUser` model
- [x] Added test
- [x] Changed existing implementation to  `user.get_form_label()`
- [ ] But I did not change asssert in the initial value in `projectroles.tests.test_views.TestProjectCreateView` as there is another logic without this function

**Comment by gromdimon** [comment]
Will be happy for any comments

**Comment by mikkonie** [comment]
Done by @gromdimon and merged.
