### ISSUE TITLE
Add logging friendly Project title getter

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1071]
In many places, we use a manually built logging-friendly notation for the `Project` mode. This is in the following format:

```
'"{}" ({})'.format(project.title, project.sodar_uuid)
```

To reduce repetition in code and improve logging consistency, this should be added as a helper into the `Project` model. It should **not** replace `Project.__str__()`, because that has other uses and is more helpful in e.g. the Django shell.

## Tasks

- [ ] Add the helper as `Project.get_log_title()`
- [ ] Add test(s) in `projectroles.tests.test_models`
- [ ] Update usage in SODAR Core

**Comment by gromdimon** [comment]
- [x] Added helper function get_log_title()
- [x] Added test_get_log_title
- [x] Updated usage in Sodar core
The only thing is  projectroles/remote_projects.py:441. There is no retrieving the whole Project, thus I let it just as is.

**Comment by gromdimon** [comment]
Changes are in dima branch

**Comment by mikkonie** [comment]
Done by @gromdimon
