### ISSUE TITLE
Add UI tests for timeline event details and extra data

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1081]
When re-implementing timeline extra data retrieval, old UI tests were removed as they were no longer applicable. Meanwhile, event detail UI tests never existed in the first place.

We should add some sanity checks in UI tests to ensure the data for both event detail and extra data modals gets correctly displayed.

I recommend doing this at the same time or after #873.

## Tasks

- [x] Add tests to assert event details are correctly displayed
- [x] Add tests to assert event extra data is correctly displayed
- [x] Add tests to assert extra data clipboard copying works

**Comment by mikkonie** [comment]
One small issue I noticed after merging: `test_copy_button()` does not check the clipboard content after clicking. You should ensure the expected value is found in the clipboard after clicking.

Feel free to add this to some ongoing timeline-related pull request, doesn't have to be a separate one :)

**Comment by mikkonie** [comment]
Done by @gromdimon, and as he correcly pointed out, clipboard content can't be checked without unnecessary workarounds. Closing.
