### ISSUE TITLE
Add project deletion

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1090]
This was originally a part of #369, but it was split into a different task.

## Spec

- Allow deleting project for real
- Make action available to owner and delegate
- ONLY allow this for category if it has no children
    * In case of children, they have to be manually deleted
    * We don't want to make it too easy to accidentally delete a whole tree of categories and projects
    * If not allowed for this reason, display UI control as disabled with tooltip explaining why
    * Also prevent access to view in such a case (and test!)
- Add confirmation step
    * Note that this can NOT be undone
    * For projects, also note that all data will be deleted
    * Host confirmation similar to project data deletion in the SODAR sampleheets app
        + ~~Make this into a common helper, use also in SODAR~~ split into #1550
    * Notify of project on target sites, if any
        + Note that access will be revoked on target sites
- Add deletion hook to `ProjectModifyPluginMixin` and appropriate call in delete view
    * No need for revert as this explicitly can't be undone
- Create app alerts and email to all members other than user performing the action
    * Check `notify_email_project` setting of user on whether to alert
- Create summary timeline event of deletion
    * Site scope, classified=True
    * Because timeline events will be deleted along with the project, otherwise we will not have any audit trail left for this
- Revoke access for project on target sites if remote projects exist
    * ~~`RemoteProject` object needs to support `project==None` for this~~ Oh wait it already does
- Add delete API view
    * I thought long about whether or not to add this, but there are use cases for automating project deletion (e.g. writing API scripts to split projects into multiple ones and deleting the original, or deleting all of a user's test projects) it should be included.
- If on target site and remote project, only allow deletion if access has been revoked

There is also a possibility to add a "soft delete" option where we don't exactly delete anything but simply remove access. I haven't heard about demand for this though, and we already allow hard deleting data in SODAR, so I'm just going with this option for now. If needs for this are voiced, we can expand to a soft deletion feature later.

## Tasks

- [x] Add delete UI view and UI/API mixin for basic deletion
- [x] Add app alert creation
- [x] Add timeline event creation
- [x] Add email sending
- [x] Add and test category access limitations
- [x] Add remote site logic and tests
- [x] Add UI logic for enabling/disabling access to view
- [x] Add UI view permission, view and UI tests
- [x] Add site hostname confirmation
- [x] Add ProjectModifyAPI hook and call
- [x] Add API view
- [x] Add API view permission, view and UI tests
- [x] Ensure everything is properly documented

**Comment by mikkonie** [comment]
Done.
