### ISSUE TITLE
Add event status extra data to event details modal

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1096]
Timeline `ProjectEventStatus` objects also have their own `extra_data` field, which can be used to store extra data for a specific status update in the event lifecycle.

In the previous implementation these were loaded together into the server-side modal we got rid of. In the new implementation, we are not yet displaying these. IMHO the most logical place for these to go UI-wise is the event detail modal, on the right hand side of the "description" field similar to the event list.

**NOTE:** This should be done as a separate pull request from the timeline tasks under work at the time of writing.

## Spec

- If status object has extra data, add extra data link to the status in the event details modal
- Once clicked, the modal should:
    * Display `sodar-modal-wait`
    * Query for extra data from an Ajax view
        + Probably it's easier to re-use the existing extra data ajax view for this, just allow it to also return extra data for a `ProjectEventStatus`
    * Once data is returned, render extra data modal content with the status extra data

## Tasks

- [ ] Add `ProjectEventStatus` extra data retrieval in view
- [ ] Implement logic in modal
- [ ] Add view, permission and UI tests

**Comment by mikkonie** [comment]
Done by @gromdimon, closing.
