### ISSUE TITLE
Review and update tour help text for all views

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1102]
I have neglected tour help lately. I need to go through the help texts for each view to ensure they are up to date.

## Checklist

- Is the text still correct?
- Are all current and relevant features of the view covered?

## Tasks

- [x] Update existing projectroles templates
- [x] Add tour help to `projectroles/remote_sites`
- [x] Add tour help to `projectroles/remote_projects`
- [x] Update existing filesfolders templates
- [x] Update existing timeline templates
- [x] Add tokens tour help
- [x] Add appalerts tour help
- [x] Add userprofile tour help
- [x] Fix double quotes in `get_display_name` template tag calls

**Comment by mikkonie** [comment]
Done.
