### ISSUE TITLE
Add sodar_uuid field and usage to ProjectEventStatus model

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1112]
The `sodar_uuid` field was originally left out from the timeline app `ProjectEventStatus` model, as these models were not often directly accessed. With the ongoing addition of #1096, this is no longer the case. With event status extra data being queried via Ajax from server side, we now have to use an index-based query which is not very SODAR Core-ish.

Instead, we should add the standard UUID field and update the event status extra data Ajax views to use direct references to the `ProjectEventStatus` model.

**NOTE:** Since this feature requires working with migrations, I strongly recommend working on it after all the ongoing PRs have been closed, as moving back and forth between work branches with different migrations can be very painful.

## Spec

- Add `get_project()` method to  `ProjectEventStatus`
    * Should return `event.project`
    * This is needed for SODAR Core project access mixins
- Add `sodar_uuid` field to `ProjectEventStatus`
    * The field needs to be manually populated in migrations, see [here](https://sodar-core.readthedocs.io/en/dev/dev_project_app.html#model-uuid-field) and [here](https://docs.djangoproject.com/en/3.2/howto/writing-migrations/#migrations-that-add-unique-fields) for more information
- Update timeline extra data views and their usage to take a direct `ProjectEventStatus` reference instead of `ProjectEvent`and an index
    * Update link creation for views accordingly, of course
- Update tests as needed

## Tasks

- [ ] Add `get_project()` method
- [ ] Add and populate `sodar_uuid` field
- [ ] Update views and usage
- [ ] Update tests

**Comment by mikkonie** [comment]
Done by @gromdimon.
