### ISSUE TITLE
Update URL patterns to use path instead of regex where applicable

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1116]
Since implementing #1047, there should be no problem in replacing the URL patterns for `sodar_uuid` URLs with a path syntax instead of the traditional regex. This should make the URL definitions look a lot more readable.

**NOTE:** This is a low priority issue, good to do when e.g. waiting for feedback for some larger task, or if I'm slow to assign stuff and you run out of other tasks :)

## Spec

- In all apps, update `regex` URLs to use `route`
  * As an example, `regex=r'^update/(?P<project>[0-9a-f-]+)$'` would become `route='update/<uuid:project>'`.
  * Preserving the original kwarg names is critical, as those are used by `ProjectAccessMixin` to determine perms.
  * There might be some 
- **Exception:** Leave URLs in `example_project_app` as is, because in there we ensure the working of both regex and path URLs
- Running existing tests should catch any problems with forming URLs in case there's a mistake or typo.
  * No new tests should be required.
- Docs and examples within should be updated to reflect that the recommended way of setting URLs is using `route`, but `regex` also works.
  * See [dev_project_app.rst](https://sodar-core.readthedocs.io/en/dev/dev_project_app.html#url-keyword-arguments)

## Tasks

- [ ] Update URL patterns
- [ ] Ensure tests run
- [ ] Update docs as needed

**Comment by mikkonie** [comment]
Done by @gromdimon.
