### ISSUE TITLE
Add project limiting to search

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1191]
We should be able to limit search results by project UUID. Not sure why this was never implemented.

**Update 2026-02:** This has also recently been requested (again) by a SODAR power user. Let's go ahead and do it.

How this should work:

- User makes a search with keyword `project:{Project.sodar_uuid}`
   * Example: `search term project:6bffad6d-93ad-402b-bb7d-0da269f9ee5b`
- Search only returns items related to the project with the given UUID.
- We should also update search functionality in SODAR Core apps to handle this keyword.

By using the `keywords` kwarg in search, this will not be breaking. We should first do #1894 though to ensure the kwarg is presented correctly in the API.

This will not be breaking, as the `keywords` kwarg already exists. However, this hands over the responsibility for providing expected results to the apps implementing `search()`.

We *could* also add filtering in `ProjectSearchMixin._get_app_results()`. However, we can't guarantee that every model in apps implemented by SODAR Core based sites has a `ForeignKey` with the name `project`. Also, some apps require logic unknown to SODAR Core in filtering results, like searching for iRODS files in SODAR. Last but not least, this would perform much worse than apps handling the filtering themselves. Hence, IMHO, we should trust the apps to handle this and simply document the expected behaviour. Let me know if you disagree.

## Spec

**Update 2026-03-05:** Updated according to discussions related to #1899.

- Add `projects` argument to `ProjectAppPlugin.search()`
    * Type = `QuerySet[Project]`
    * Mandatory, goes after `user`
- Populate `projects` argument in `ProjectSearchResultsView`
    * IF `project` keyword is given, QuerySet is `Project.objects.filter(sodar_uuid=keyword_value)`
    * ELSE `Project.objects.all()`
    * (More fancy filtering will be done in #1898 and beyond..)
- Pass new arg to plugins in `ProjectSearchMixin`
- Update `find()` methods in object managers to filter projects down to the `projects` arg
    * `projectroles.models.ProjectManager`
    * `filesfolders.models.FilesfoldersManager`
    * `timeline.models.TimelineEventManager`
- Handle invalid UUIDs gracefully, e.g. don't return anything
- Update tests for all three apps to ensure filter is properly handled
    * Remember to also test with invalid/missing UUID :)
- Update documentation
    * `app_projectroles_usage.rst` under "Search"
        + Add mention of `project` keyword
        + Maybe reorganize this nicely together with the `type` keyword?
    * `dev_project_app.rst` under "The search() Function"
        + Mention that there is currently one supported keyword for `keywords`, `project:uuid`
    * `major_changes.rst`
        + Add breaking change note for `projects` argument in `search()`
        + Note that apps are expected to implement filtering for the `projects` queryset in `search()`
    * **TBD:** Any mentions anywhere else I missed?

## Tasks

- [ ] Fix #1894 
- [ ] Add `projects` kwarg to `search()`
- [ ] Add filtering by project queryset in `ProjectManager.find()`
- [ ] Add filtering by project queryset  in `FilesfoldersManager.find()`
- [ ] Add filtering by project queryset  in `TimelineEventManager.find()`
- [ ] Update projectroles tests
- [ ] Update filesfolders tests
- [ ] Update timeline tests
- [ ] Update documentation

**Comment by fmarotta** [comment]
Would users be confused if they use the project name instead of UUID and get no results back? Should we maybe call the keyword `project_uuid` or do you think that `project` is fine as long as it's documented?

**Comment by mikkonie** [comment]
> Would users be confused if they use the project name instead of UUID and get no results back? Should we maybe call the keyword `project_uuid` or do you think that `project` is fine as long as it's documented?

This is a good point. We discussed this privately and I agree it might be a good idea to support project title here.

However, I think it's easier if we do it in a separate PR once we finalize this one. New issue here: https://github.com/bihealth/sodar-core/issues/1898

**Comment by mikkonie** [comment]
Done by @fmarotta, merged.
