### ISSUE TITLE
Refactor permission tests for new conventions

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1267]
See the `samplesheets` app in SODAR for current standards. Also see bihealth/sodar-server#1739.

## Spec

- Split tests per view class
- Follow consistent method naming and docstrings
- Set URL in class to avoid repetition where applicable
- Use `cleanup_method` and `setUp()` set up things, remove unnecessary iteration within actual tests

## Tasks

- [x] Update tests in `adminalerts`
- [x] Update tests in `appalerts`
- [x] Update tests in `example_project_app`
- [x] Update tests in `filesfolders`
- [x] Update tests in `projectroles`
- [x] Update tests in `siteinfo`
- [x] Update tests in `timeline`
- [x] Fix `timeline` Ajax view permission test problems
- [x] Update tests in `tokens`
- [x] Update tests in `userprofile`

**Comment by mikkonie** [comment]
Done. I also added a lot of missing tests and fixed problems in the timeline Ajax view permission tests.
