### ISSUE TITLE
Unify project badges into a common reusable badge

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1300]
Project badge HTML is needlessly repeated between appalerts and timeline. Instead, there should be common badge include in projectroles to be used in different apps.

This can be nicely done together with #1299.

## Tasks

- [x] Add common include template
- [x] Update usage
- [x] Update references to `sodar-tl-item-project-badge` and `sodar-app-alert-project-badge` in tour help and tests
- [x] Test with all badge colors to ensure layout is OK
- [x] Test truncating
- [x] Clean up templates
- [x] Remove `timeline/_project_badge.html`
- [x] Add docs
- [x] Update changelog and readme

**Comment by mikkonie** [comment]
Done.
