### ISSUE TITLE
Add site settings site app plugin for admins

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1304]
This is needed for #24. This should be a simple form view where we can edit (user modifiable) site settings as an admin. Later on we can make it into some fancier dashboard-style thing (see #154).

Since this is, at least initially, a single simple form, this should be an additional site app plugin in `projectroles` instead of a separate app. That also goes because with things like a site-level read-only setting, it can't really be optional.

## Spec

- Create site app plugin within projectroles
    * Access only for superusers
    * Form view should be the entrypoint (and only view)
- Create form view
    * Initially just an empty template so we can get things going
- Create form
    * Reduce reuse between this, `ProjectForm` and `UserSettingsForm`
        + There is a lot of repetition for app settings between the two existing forms
- Add tests
    * View, permission, UI 
- Add documentation

## Tasks

- [x] Create app plugin
- [x] Create view
- [x] Add highlighting to `get_user_links()`
- [x] Create form
- [x] Add tests
- [x] Add documentation
- [ ] ~~Refactor app settings forms to remove repetition~~ To be done in a separate ticket

**Comment by mikkonie** [comment]
Done.
