### ISSUE TITLE
User dropdown plugin link highlight fails with certain plugins

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1331]
The highlight works for e.g. `example_site_app` and `userprofile`, but fails for `tokens` and `timeline` site-wide events. Must figure out why. This bug has probably been there for a while.

## Tasks

- [x] Fix template tag to not require exact app name
- [x] Add missing URL patterns to apps
- [x] Provide correct URL patterns to multi-plugin apps
- [x] Do #1332 
- [x] Do #1334 
- [ ] ~~Add timeline admin object view url path, update usage in templates~~
- [x] Rename `timeline_site_admin` URL name
- [x] Add documentation on how to handle multi-plugin apps (naming, URL patterns)

**Comment by mikkonie** [comment]
This turned out to be a combination of several bugs, with no 100% foolproof fix. I will have to update guidelines for plugin development in the documentation as well.

**Comment by mikkonie** [comment]
Fixed, with one caveat: timeline object URLs followed through the admin site view do not highlight the admin app in the user dropdown. Fixing this would have required way too much refactoring, as the URL is determined deep within `TimelineAPI` helpers. We'll just have to live with that :)
