### ISSUE TITLE
Enable/disable remote project links based on target sync status

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1358]
Currently there is a bit of an issue with failed project syncs. Consider the following:

- Remote sync is allowed for a source site for a project
- Remote project links in the projects detail view on source site are made active
- Sync on the remote site is slow, or not working for some reason (e.g. wrong site version, Celery worker not running).
- The aforementioned links on the source site thus don't work before the sync has finished

This creates confusion, as the projects should be synced but the links will result in errors. Hence we should enable/disable these links based on the actual sync status.

Alas, we don't currently know on the source site when the remote site has been updated vs. when it was last synced. A simple solution could be as follows:

- In project detail view, check `RemoteProject.date_access`
- If `date_access` is not `None`, enable button
- (To make this even fancier, make a JQuery check this via an Ajax view and update without having to reload the view)

The aforementioned solution is not perfect: if members have been added on the source site but sync has not yet happened, a user might still see the button enabled. If we want to take this into consideration, we could also check the latest date of user modification in the project via the timeline and compare `date_access` to that.

For starters, let's just do a check based on `date_access`. It should be OK for most cases and definitely helps with owner/delegate using the self-service feature introduced in #817.

## Tasks

- [x] Disable non-accessed projects in template by default
- [x] Add Ajax view for querying status
- [ ] Add JQuery to update status on the client side
- [ ] Add/update tests
- [ ] Update docs where applicable

**Comment by mikkonie** [comment]
Done.
