### ISSUE TITLE
Remove SAML support

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1368]
The SAML package we currently use will no longer work once we upgrade to Django 4.2, see #880. In the near future we plan on adding OpenIDC support, see #1367.

I asked around, and there is only one known instance of a SODAR Core based project currently using SAML. They are using an old version, in no hurry to upgrade and once they do, they'll be able to switch from SAML to OpenIDC.

Hence, there seems to be no reason to keep around SAML support. I will hence be removing it from v1.0.

If there is a specific need for SAML in the future (which is very doubtful IMHO), support can be re-implemented using a modern and maintained Django package.

## Tasks

- [x] Remove template/view additions
- [x] Remove settings
- [x] Remove dependencies
- [x] Remove tests (if any)
- [x] Update docs to say this will be replaced by OpenIDC
- [x] Update major changes doc

**Comment by mikkonie** [comment]
Done.
