### ISSUE TITLE
Refactor user dropdown logic into reusable component

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1381]
Sequel to #1380, also needed for #1366.

Similar to the sidebar, we want to be able to provide the user dropdown links also in an Ajax view for possible client side UIs. And similar to the sidebar, the logic for the dropdown is contained in the context processor, template and template tags.

So, you guessed it: we need to refactor the user dropdown in a similar way to the sidebar.

## Spec

- Add `get_user_links()` method to `AppLinkContent` helper created in #1380
    * `request` should probably be the only arg required
    * Return list of dicts similar to the method in #1380
- Move logic from `_site_titlebar_dropdown.html` and related template tags into new method
- Deprecate `site_app_processor()`
- Add wrapper template tag to retrieve list into `_site_titlebar_dropdown.html`
    * Call it and render the dropdown links in the template
- Add tests for new helper class
- Add/update UI tests
    * I'm not sure if we have UI tests for the menu? If not, a new class should be added next to `TestProjectSidebar`. Testing with both regular user and admin
- Remove unused template tags (if any)

## Tasks

- [ ] Add helper class
- [ ] Move user dropdown logic into class
- [ ] Deprecate `site_app_processor`
- [ ] Update tests
- [ ] Remove unused template tags (if any)

**Comment by mikkonie** [comment]
Done by @gromdimon and merged.
