### ISSUE TITLE
Add management command to remove user roles

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1391]
We should have a management command to remove all roles from a user. This is for cases where e.g. a user has left the organization and their account is no longer active.

When we eventually introduce the admin "dashboard" this should be also doable via UI, but initially let's do it via a management command.

At least initially, we should **not** delete the user object This can result in unexpected cascading of objects with a `ForeignKey` relationship to the user, which other users should still have use for.

## Spec

- Add management command to remove user roles by username
- The command should go through the same mixins regular role removal does, including calling the modify API
- Owner roles can't be removed
    * The admin can supply the username of a user for which owner roles are to be transferred
    * If not supplied, each local owner role should be assigned to the owner of the parent category
    * If the new owner already has local non-owner role in project, promote that
    * Ensure parent owner is not the user we're removing (shouldn't happen if we iterate by `Project.full_title`)
- Prevent running on remote projects

## Tasks

- [x] Add command
- [x] Update `RoleAssignmentDeleteMixin` to support the command
- [x] Add functionality for non-owner roles
- [x] Update `RoleAssignmentOwnerTransferMixin` to support the command
- [x] Add functionality for owner roles
- [x] Add/update tests
- [x] Add/update documentation

**Comment by mikkonie** [comment]
It seems this somewhat overlaps with #836, so some refactoring related to that issue will be done within this feature.

**Comment by mikkonie** [comment]
Done.
