### ISSUE TITLE
Prevent sending invite to email with existing invite for parent category

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1403]
I just noticed a user sending two invites to a non-user via email: one for a category and one for a project under it.

Naturally, the latter is redundant, with the exception of cases where the project role is intended to be a higher one than the category. But even in that case the role should be granted to the user after they have logged in.

We should prevent the sending of redundant invites. I'll write a complete spec later.

To make it really fancy, we could also set it so that accepting a redundant but promoting invite would simply grant that role, but let's start with this one.

## Spec

- IF invite is created AND a user has invite in parent category AND invite is active
- THEN fail creation with an error message

## Tasks

- [x] Add logic to UI view
- [x] Add logic to API view
- [x] Update tests for UI and API views
- [x] Update docs where applicable

**Comment by mikkonie** [comment]
Done.
