### ISSUE TITLE
Move projectroles base test classes and helpers to base module, deprecate existing

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1431]
We should consider moving projectroles base test classes and helpers, which are expected to be used in SODAR Core using sites, into base module(s) instead of having them in the same module as SODAR Core specific test cases.

IMHO this would make it easier to manage base classes and helpers, differentiate them from tests and make the test case modules less bloated. As an example, one can look at the projectroles UI tests where the helpers take up quite a bit of the already rather large module. 

This is something I have already done in SODAR with taskflowbackend tests and it clarified things a whole lot.

I'll still have to think further about whether this is a good idea or not, this issue is moslty intended as a note-to-self. Comments are welcome of course. This will not be done before at least v1.1, hence the tag.

See also #1253.

**Update:** I decided to do this via deprecation similar to #1460.

## Tasks

- [x] Move `test_views.ViewTestBase`, update uses
- [x] Cleanup `test_views` constants
- [x] Move `test_views_api.*`
- [x] Cleanup `test_views_api` constants
- [x] Move `test_permissions.*`
- [x] Move `test_permissions_api.*`
- [x] Move `test_ui.*`

**Comment by mikkonie** [comment]
I'm moving the test reworking issues to v1.3, as v1.2 is becoming quite bloated already.

**Comment by mikkonie** [comment]
Done.
