### ISSUE TITLE
Remove migrations squashed in v1.0

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1455]
Remove migrations squashed in v1.0, see #1446.

**Note:** This will require the site to be deployed/migrated on v1.0 prior to upgrading an existing version to v1.1. This needs to be mentioned in the major changes documentation.

## Tasks

- [x] Remove squashed migrations from projectroles
- [x] Remove squashed migrations from adminalerts
- [x] Remove squashed migrations from bgjobs
- [x] Remove squashed migrations from filesfolders
- [x] Remove squashed migrations from sodarcache
- [x] Remove squashed migrations from timeline
- [x] Update major changes doc

**Comment by mikkonie** [comment]
Done.
