### ISSUE TITLE
Set up app setting definitions as objects

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1456]
As with many return values of implementable plugin methods, expecting these as dictionaries offers a lot of chance for user error and ambiguity.

We should set up a class for app settings and expect definitions to take form of a list of objects instead of a dict.

This also allows us to place critical validation in the class `__init__()` to detect badly defined settings as early as possible.

Providing app settings as a dict should be deprecated with warning in v1.1 and removed in v1.2.

Existing setting dicts within SODAR Core should be replaced with the class objects, of course.

## Tasks

- [x] Add `PluginAppSettingDef` class
- [x] Update usages and existing definitions
- [x] Allow dict definitions with deprecation warning
- [x] Fix test failures from initial commit
- [x] Fix `[Not editable on target sites]` label visibility
- [x] Rename misleading `s_val` variables
- [x] Remove redundant `s_key` variables
- [x] Add default value validation on model level
- [x] Add Django check for name uniqueness within plugin
- [x] Update tests
- [x] Add model tests for `PluginAppSettingDef`
- [x] Update docs and examples

**Comment by mikkonie** [comment]
Done.
