### ISSUE TITLE
Projectroles: Implement TestPermissionBase as a mixin

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#147]
The current `TestPermissionBase` class inherits the standard `TestCase` class and thus cannot be used with taskflow test cases.

It should instead be a mixin inherited by `TestProjectPermissionBase`.

## Tasks
* [ ] Refactor as mixin
* [ ] Remove `assert_render200_ok()` and `assert_redirect()`, replace use with `assert_response()`
* [ ] Add `POST` data support in `assert_response()`
