### ISSUE TITLE
Add support for API schema generation with drf-spectacular 

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1508]
This seems to be the FOTM and Varfish is using it. I already looked into adding support a bit regarding #1505, doesn't seem like too much work. Alas, I'd prefer not introducing new dependencies and apps in a `..1` unless I really have to, so tagging this for v1.1.

This is a breaking change as it will cause `./manage.py generateschema` to stop working. It should be documented as such.

## Tasks

- [x] Add dependency and install app
- [x] Add Makefile endpoint
- [x] Fix sodarcache views
- [x] Fix filesfolders views
- [x] Fix projectroles views
- [x] Fix timeline views
- [x] Find way to ignore knox views
- [x] Update release checklist
- [x] Document breaking change

**Comment by mikkonie** [comment]
Done.
