### ISSUE TITLE
Add ProjectCache backend app

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#169]
**NOTE**: This description is WIP and will most likely change by the time you've read it, in case you see this text here :)

When planning sodar-server##241 I realized that it's better to do a generic cached/aggregated data storage backend app, rather than implement a specific one for Samplesheets/iRODS and end up generalizing it anyway.

Some caching components for Django exist but they seem to be mostly tied to internal Django db QuerySet caching. This doesn't have to be overly complex either, so let's just implement our own SODAR based solution.

## General Concept

- Implement as backend app
- Get/set data via the backend API instead of direct Django object manipulation
    * Similar to e.g. timeline
    * So we are free to e.g. optimize the database itself if needed
- Also add Ajax views for data get/set (with project access control though)
- Should support entry of the actual data values in different formats
    * E.g. abstract data model -> concrete ones
    * Initially we only need to support JSONFields as that's best for the initial use case
    * The cache backend app should not be concerned with the data values themselves (unless the format is wrong for the db table)
- Setting the data is handled by apps themselves
    * Ideally async using background jobs
- App plugins implement a function which can be called to update data
    * In case of e.g. db wipe and re-population from a management command
- ..oh yes, this app will have a management command (or several) to update data
- For cached data so it's not guaranteed to be consistent! (can be re-generated at any point)
- If needed, some sort of expiry mechanism could also be added
    * Or just let the requester handle it
- Mostly for project-specific data, but let's make it also possible to have non-project-specific data
    * For e.g. site-wide statistics (could be used with #18!)

## Example Use Case

1. A data-modifying flow finishes in SODAR Taskflow
2. Taskflow calls an API view to update cached iRODS data for the project
    * **TBD:** Call a single ProjectCache API view which passes on data updating request to app, or leave this up to the app itself?
3. API view calls related updating function(s) (and returns OK immediately)
    * Possibly calling multiple nested functions e.g. in case of nested study/assay apps
    * This code creates an async bgjob to handle it
4. Possible existing data with the same project/app/id gets replaced
5. User requests a page, client gets fresh cached data
    * If cached data is not found or has expired, do the actual queries or do nothing, depending on the use case

## Data Model

Everything WIP (duh). Many fields can be copied as is from existing SODAR Core models, let's maintain consistency where we can :)

- `BaseCacheItem`: abstract model
    * `project`: models.ForeignKey(Project)
        + NOTE: `null` must be allowed!
    * `app`: models.CharField
        + Corresponds to APP_NAME
    * `name`: models.CharField
        + Identifier for the item given by the data setting app
        + Should be unique within project & app
    * `date_modified`: models.DateTimeField with autofill
    * `user`: models.ForeignKey(User)
        + The previous updater, just in case it's relevant
    * `sodar_uuid`: models.UUIDField with autofill
        + Make sure to add this before the first migration, autofilling unique UUIDs are a *major* pain to modify in Django..
    * **TBD:** An expiry datetime field? (or do we leave this up to logic in the calling app?)
    * **TBD:** Description/comment field?
- `JsonCacheItem`: concrete model implementing BaseCacheItem (surprise!)
    * `data`: JSONField

## APIs for Updating Data

- ProjectAppPluginPoint function to be implemented in app ProjectAppPlugin:s
    * E.g. `update_project_cache()`
    * Arguments
        + `project` (Project object of course)
        + `name=None` (Name of field to update: if None, update *all* cache items known to the app)
- Management command to call the function in all apps without the `name` param
    * NOTE: Should not crash if the function has been implemented in an app
        + This shouldn't be an issue as long as we define the function in the plugin point)
    * For an example of a management command, see e.g. `syncroles` and `synctaskflow`
- Taskflow API view in sodarprojectcache for triggering update with a certain name/ID
- Taskflow task for calling the aforementioned API view

## Tasks

* [x] Set up backend app (see docs)
* [x] Implement model
* [x] Implement backend API (see e.g. timeline and irodsbackend for examples)
* [x] Implement API views
* [x] Implement ProjectAppPluginPoint update function (see above)
* [ ] Implement management command for calling the update functions
* [ ] Implement update function in samplesheets for updating stats/collections (sodar-server##241) Note: This also needs to internally call some similar functions in study app plugins!
* [ ] Implement Taskflow API view
* [ ] Implement sodar_taskflow task for calling the API view, add to relevant taskflows

**Comment by mikkonie** [comment]
unassigned @fefschumann
