### ISSUE TITLE
Update SODAR Core to Django 3.1

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#194]
LTS support for Django 1.11 has ended. Not only do we not get security updates anymore, 3rd party packages are dropping support fast.

We finally need to bite the bullet and upgrade SODAR Core, along with ALL projects based on it, to the latest and greatest Django version.

Initially we should target the current bleeding edge version (3.1). In the future we should try to keep up with the latest stable version, unless there are convincing reasons (e.g. critical third party app not yet updated to support the latest release)

## Resources

- [Django deprecation docs](https://docs.djangoproject.com/en/dev/internals/deprecation/)
- [List of 1.11-2.x updates](https://nezhar.com/blog/upgrade-a-django-based-application-from-1-11-to-2-0/)

## Tasks

- [x] Upgrade Django
- [x] Upgrade django-plugins
- [x] Refactor what is needed
- [x] Upgrade all Python requirements
- [x] Test site functionalities in browser
- [x] Fix pagedown edit bar background
- [x] Fix DAL autocomplete to omit users already in project
- [x] Fix DAL redirect to work with new API

I will initially do this in a separate `dev10` branch as this *will* break stuff, hard.

## How to Upgrade Your SODAR Core Based Site

(Once upgrading requirement to SODAR Core v0.10)

- Make sure you're running PostgreSQL >=9.5
- **Recommended:** Back up your database
- **Recommended:** Set up separate database for the upgrade
- **Recommended:** Set up separate virtualenv for the upgrade
- Upgrade Python requirements to match `requirements/*.txt`
- Declare `on_delete` argument for each `ForeignKey` field in your models
- Replace `is_authenticated()` and `is_anonymous()` calls with `is_authenticated` and `is_anonymous`
- Replace imports from `django.core.urlresolvers` with `django.urls`
- Replace `django.contrib.postgres.fields.JSONField` with `django.db.models.JSONField`
- If using `PageDown`, replace `PagedownWidget(show_preview=False)` with `PagedownWidget(attrs={'show_preview':False})`
- Make migrations and migrate
    * **Recommended:** You might want to rename some `auto_*` migrations for clarity
- Wipe your project's existing `staticfiles` directory
- Run tests and observe results
    * Make sure your test script always runs `collectstatic` before the tests!

It's possible you'll run into other problems with deprecated Django features. [See deprecation guide here](https://docs.djangoproject.com/en/dev/internals/deprecation/)
