### ISSUE TITLE
Remove app settings from category create/update

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#20]
Currently, project-scope app settings are always visible in the project creation/updating form. However, settings are linked to project app plugins, which are not available for category-type projects. In practice, we set app settings for categories which have no effect. These are also set when creating/updating a category via REST API views.

This needs to be changed. If the project type is `CATEGORY`, app settings should not be included in the form and not set.

The tricky part? The project type is selected within the form (except when creating a top level category). This means we'll have to do some JQuery trickery to show/hide the relevant form fields based on the user selection.

In the future, we can change this so that these can be set in the category and settings propagate to child categories/projects. This will have to be communicated clearly to the user, of course.

## Spec

- Add JQuery to hide app settings fields if `CATEGORY` is selected as project type
    * Add to a new `project_form.js` file only loaded in `project_form.html`
    * Show the fields if `PROJECT` type is set, of course
- Disable setting app settings in project update form/view if project type is `CATEGORY`
    * In `ProjectModifyMixin.modify_project()`, do not call `_update_settings()` if type is category
        + **NOTE:** This will also disable setting the app settings for REST API views
    * We should be able to skip the "Verify settings fields" part of `ProjectForm.clean()` if category

## Tasks

- [x] Update form UI to hide/show app settings fields if category
- [x] Update `forms.py` to not set app settings if category
- [x] Update tests for category creation/update as needed
- [x] Add UI test(s) for testing the hiding/showing

**Comment by mikkonie** [comment]
Done by @gromdimon.
