### ISSUE TITLE
Projectroles: Sync peer target project information into target sites

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#200]
Needed for #196. Currently a target site only knows about the source site. We need for target sites to be aware of "peer" target sites sharing rights to the same projects. This is done so we can e.g. provide linking to the projects as well as provide app API access between target sites in the future.

## Plan

- Add a third possible value to `RemoteSite.mode`: `SITE_MODE_PEER`
- On a SOURCE site, when syncing remote projects to a TARGET:
   * IF other target site/sites have `REMOTE_LEVEL_READ_ROLES` or `REMOTE_LEVEL_READ_INFO` access to a project
   * THEN add reference to the remote site(s) in the remote project data
   * AND add data about the remote site to a separate "remote sites" list, if not yet there
     + Required info to create a `RemoteSite` object on the TARGET site
- On a TARGET site, when on the other end of said transaction
   * In addition to the existing remote sync procedure..
   * Iterate through the remote sites list, create `PEER`-type `RemoteSite` objects for those not yet listed
   * Iterate through projects
       + IF a project has a remote site reference and a related `RemoteProject` object doesn't exist
       + THEN create a `RemoteProject` objects for the projects in question
   * On the project details page on the TARGET site, show links to the `PEER` projects (as long as the display flag is set True and only if the access level is `REMOTE_LEVEL_READ_ROLES`, not for `REMOTE_LEVEL_READ_INFO`)
- **If possible**, do this change so that data is only added to the sync API - no modification of existing data
   * With this, TARGET sites not yet upgraded to the SODAR Core version with this update should still be able to sync projects without errors
   * That said, refactoring the current (very ugly and hasty) remote project API code is perfectly fine. Same goes for the tests.

I've probably forgotten something or made gross generalizations, but I'll flesh this out early next week if needed.

## Tasks

(Very general for now)

- [x] Add support for the `PEER` site mode
- [x] Add peer site/project data to the project sync when in SOURCE mode
- [x] Add handling of the peer site/project data when in TARGET mode
- [x] Add display of peer project links to the UI on TARGET sites
- [x] Update tests
- [x] Test new peer mode and UI
  - [x] Test `get_target_data`
  - [x] Test `sync_source_data`
  - [x] Assert correct display of Peer Sites on TARGET site Project Details
  - [x] Test get_peer_project tag
  - [x] Assert PEER Project are neither created nor displayed on SOURCE site
- [x] Update docs
- [x] `user_display` to toggle visibility of `Peer` sites as well

**Comment by mikkonie** [comment]
unassigned @timgarrels
