### ISSUE TITLE
Cleanup for v0.5.1 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#214]
## Tasks

* [x] Fix "get_mesasges()" typo in dev_site_app.rst (thanks Oliver :))
* [x] Remove redundant `<!-- Settings -->` comment from `base_site.html`
* [x] Fix indentation in `base_site.html`
