### ISSUE TITLE
Add site read-only mode

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#24]
(Updated in 2025-01)

We need to implement a "read only mode" across all projects, This can be initiated by an admin before deploying updates. This way we won't break e.g. long-running async landing zone jobs.

Also, if there is a known issue regading some data updating functionality, this can be used to temporarily prevent changes while still keeping the site up for data access.

## Spec

- Add site setting for read-only mode
    * Not global, default=False
- Add check for read-only mode in data modifying rule predicates
- Data-modifying management commands should still be allowed, as they're ran by superusers anyway
- Add UI prevention to access views where necessary
    * For the most part, getting the "no permissions" error triggered by rule predicates should be enough    
- Add UI alert for read-only mode
    * Should auto-refresh with Ajax requests querying the status
    * Refreshed status should have a link for reloading the site (all UI updates not necessarily done in client side)
    * Make alert text configurable in Django settings
- Add Ajax view for querying setting status
    * Can't do a generic site setting API/Ajax view before we introduce some privacy controls (see #974)
- Update tests
    * Permission tests!
    * Others where applicable
- Document this well for developers
    * List steps to do to add support in their sites
    * Note in dev docs that `can_modify_project_data` already contains check for site mode
- Do #1304 for the admin UI

## Tasks

- [x] Add setting
- [x] Update rule predicates
- [x] Update projectroles permission tests
- [x] Update rules and permission tests in other apps
- [x] Add alert message
- [x] Add Ajax view for mode status check
- [x] Add client-side alert handling
- [x] ~~Disable role controls in ProjectRoleView if read-only mode~~, add UI tests
- [x] Disable project starring button if in read-only mode
- [x] Disable tokens app create/delete controls if in read-only mode
- [x] Disable userprofile edit buttons if in read-only mode
- [x] Add developer docs
- [ ] Look into test errors with `projectroles.tests.test_ui.TestProjectSidebar.test_create_link_disable_categories`
- [ ] Look into test errors with `projectroles.tests.test_ui.TestProjectCreateView.test_owner_widget_sub`
- [ ] ~~Add user docs~~ (pending #1304)

**Comment by mikkonie** [comment]
Done. I'll still have to keep an eye on the random UI test issues, see #1542. Next up is doing #1304.
