### ISSUE TITLE
Projectroles: Enable project AND user specific app settings

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#266]
There are some use cases for this, e.g. sodar-server##539.

These should, of course, not be modifiable in the userprofile app form, nor the project editing form which is not visible for all users.

## Tasks

- [x] Add a third type of app settings, e.g. `PROJECT-USER`
- [x] Enable support for these types of settings in `AppSettingAPI`
    * Remove the "only user OR project setting" limitation
    * Check for the defined type for the setting -> only allow project AND user arguments if the PROJECT-USER type is defined
- [x] Make sure these settings are **not** displayed in project editing or user profile menu
- [x] Update tests to ensure these settings are handled correctly
- [x] Update docs where relevant

Let's not make a separate UI for modifying these for now. In existing use cases these are modified by UI (or backend code) of project apps already. This means the `user_modifiable` parameter will be ignored.
