### ISSUE TITLE
Projectroles: Add project link display toggle for target sites

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#276]
If project role access is given to some other sites, they are visible on the project details page. Some of the links to TARGET sites we might not want to show to users, as they might be some internal tests sites etc. (The SOURCE site should always be displayed when we're on a TARGET site))

REDACTED

## Tasks

- [x] Add a boolean `user_display` field to the `RemoteSite` model (default=True)
- [x] Add a form toggle for "display site to users" in remote site management
  - (only for TARGET sites!)
- [x] Add user visibility column in remote project details
  - (only for TARGET sites!)
- [x] Add check for site label visibility in template (**EXCEPTION:** display for owner & superuser but grayed out)
- [x] Update tests
- [x] Add UI test to ensure element is not visible if `user_display=False`
- [x] Add UI test to ensure "user visibility"-toggle (not) visible on add remote project
- [x] Add UI test to ensure "user visibility"-column (not) visible on remote project overview
- [x] Update docs

Ideally to be done together with #196, #198 and #200.

## Hints

To develop remote site functionality one will have to do the following..

- Read up on the remote site things in the docs so you'll understand the "source" and "target" concepts
- Set up a second SODAR Core database for the target site
    *  Default db name is `sodar_core_target`, you can still use the same db user for it
- Management commands for the target site can be run with `./manage_target.sh` in place of `manage.py`
- Set up a superuser account for the target site (default name expected in config is `admin_target`)
- Run both source and target sites at once, the target one using `./run_target.sh`
    * The target site can be found on http://localhost:8001
- Set up the source/target relationship for the sites using the remote project UI (see docs)
- For testing stuff as a target site, you'll have to use `@override_settings(PROJECTROLES_SITE_MODE=SITE_MODE_TARGET)` quite a bit
    * See existing tests for examples..

**Comment by mikkonie** [comment]
unassigned @timgarrels
