### ISSUE TITLE
Projectroles: Owner role modification streamlining

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#287]
Currently, editing the owner is done through the project update view, which is apparently confusing some users. We should streamline this.

Additionally, when changing ownership, the former owner should be automatically delegated with another role. Currently a new role must be manually assigned.

## The Spec

- "Create project" form
    * No changes, select owner as currently implemented
    * (Need to know owner before creating the actual project because taskflow)
- "Update project" form
    * Remove owner modification from form
    * Also remove related owner modification task from the `project_update` flow in sodar_taskflow
- "Update Member" form
    * Allow assigning owner role for users
        + Only the current owner or a superuser can be allowed to do this
    * If assigning owner role, demote current owner to a specific role
        + Let's use "project contributor" role for now
        + In the future, this could be modified in project settings
- Notes
    * All behaviour must also work with sodar_taskflow!

## Tasks

- [x] Disable owner role modification in the "update project" form
- [ ] Remove owner role modification tasks from the `project_update` flow in sodar_taskflow
- [x] Allow assigning owner role in the "update member" form (make sure only current owner and superuser have access for this)
- [x] Add automated reassigning of previous owner's role into "project contributor"
- [x] Make sure all of this also works in sodar_taskflow
- [x] Update existing tests so they pass
- [x] Add tests for owner role updating
- [x] Update projectroles usage docs
