### ISSUE TITLE
Filesfolders: Uploading a 0-size file or no file at all causes a Django crash

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#304]
Found by @timgarrels, dump attached.

Should cleanly abort the upload if the file has no content, redirecting to the filesfolders main page with a message.

## Tasks
* [x] Fix crash from an empty file (redirect to the list view with a message instead)
* [x] Make file field mandatory
* [x] Add tests with an empty file (copying from existing tests with non-empty files recommended)

**Comment by mikkonie** [comment]
unassigned @timgarrels
