### ISSUE TITLE
Projectroles: Add REVOKED access type to remote project sync

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#327]
@timgarrels raised a very good point about what happens (or should happen) on a target site when changing a remote project's access from `READ_ROLES` to `NONE`.

It was decided that the current performance is fine, except that it should be notified on the target site that roles are no longer updated.

Alas, this is not exactly trivial, because we do not sync projects with level `NONE`. Also, we don't want to sync all projects to all target sites because it might reveal metadata we don't want to reveal.

The solution is to add a new type, e.g. `REVOKED` and have the source site change the status to that instead of `NONE`, when changing from existing access to no-access-at-all. These should then be synced to the target site.

## Tasks

- [x] Add new remote project access type `REVOKED`
- [x] In the form for modifying project access for a site: if the current access type is `READ_ROLES`, replace `NONE` with `REVOKED`
- [x] Add remote projects with access type `REVOKED` to be synced in `get_target_data()`
- [x] On a target site, display an alert box (with `alert-info`) in the top of the member management function to denote that roles are not currently synchronized
- [ ] Also add some note to the UI when syncing the roles and encountering a `REVOKED` project
- [x] The usual test & docs updates

We should also make it so that once access is revoked, the project can only be accessed by superuser/owner/delegate roles on the target site. However, that would probably be too much work for the time Tim still has left working for as. I'll add it as a separate issue.
