### ISSUE TITLE
Add tests for management commands

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#352]
Certain management commands are missing tests and these should, obviously, be added.

## Tasks

- [x] Add tests for `addremotesite`
- [ ] Add tests for `geticons` (#655)
- [x] Add tests for `syncgroups`
- [ ] Add tests for `syncmodifyapi`
- [ ] Add tests for `syncremote` (1)
- [ ] Add tests for `deletecache` in sodarcache
- [ ] Add tests for `synccache` in sodarcache

## Notes

1. Needs setting up `LiveServerTestCase` with a running source server.
