### ISSUE TITLE
Add project archival

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#369]
**NOTE:** This was "add project archival/deletion", but I will move the deletion part into a separate issue.

There is a requirement to add functionality for setting projects as "archived". This means setting the project into a read-only mode where data can not be altered.

Time estimate for this (as the spec is currently written) is <1d.

## Spec

- Add `archive` field to `Project` model
- Make field editable via project edit form (with a confirmation step) as well as API
- Add `set_archival()` hook to `ProjectModifyPluginMixin`, to be called when field is altered
    * **NOTE:** This is where we could, in the future, call e.g. some data archiving functionality in SODAR
- Project role access should remain modifiable even if archived
    * Add UI note to role management views that write access will not be given even if role is contributor+
- Add visual cues to UI to denote projects are archived
- Set this up only for projects for now
    * We can add category archival later if there is demand for it
- Superuser will still retain the capability to edit data

## Tasks

- [x] Add `Project.archive` field
- [x] Add field editing to UI
- [x] Add `ProjectModifyPluginMixin` hook and usage
- [x] Add UI elements
- [x] Add perm(s) for apps
- [x] Ensure management commands are covered
- [x] Add & update tests
- [x] Update  docs

**Comment by mikkonie** [comment]
Done.
