### ISSUE TITLE
Decouple Taskflow from SODAR Core

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#387]
Originally I wrote:

*Since we are nowadays running celery jobs supported by `bgjobs`, there's very little reason to have taskflow as a separate microservice. Should just implement it as stuff within SODAR run as async jobs.*

However, I have reconsidered this given the following points:

- Taskflow functionality is, at least currently and for the forseeable future, only used by SODAR
- Implementing Taskflow and its project updating functions within SODAR Core would end up in more SODAR specific code here, while we should aim for less
- Project and role updating via callbacks is also needlessly complex and I fail to see the advantages

Thus, I propose the following solution:

- Remove Taskflow from SODAR Core entirely
- Implement Taskflow as a backend app in SODAR
- In place of current project/role updating Taskflow operations in SODAR Core:
    * Call a generic function implemented by app plugins
    * App plugin function handles extra logic if/when needed (e.g. initiating a flow in Taskflow)

There are probably some issues related to sync/async operations we'll have to overcome. I'll go through all the Taskflow-using operations once this becomes more current.

## Tasks

- [x] Replace project modifying taskflow calls with a plugin-based API
- [x] Replace role modifying taskflow calls with a plugin-based API
- [x] Replace owner transfer calls with plugin-based API
- [x] Replace invite accept calls with plugin-based API
- [x] Implement taskflowbackend in SODAR using the APIs (bihealth/sodar-server#691)
- [x] Move taskflow tests into SODAR
- [x] Remove taskflow app
- [x] Add breaking changes entry to docs on taskflowbackend plugin removal
- [x] Make sure to also remove app from install package!
- [x] Fix `batchupdateroles` (see `projectroles.tests.test_commands.TestBatchUpdateRoles`)
- [x] Create `syncmodifyapi` command to replace `synctaskflow`
- [x] Remove `get_taskflow_sync_data()` functions in plugins, refactor into project modify API
- [x] Remove taskflow mentions from timeline and other applications
- [x] Remove `sodar_url` from all APIs
- [x] Ensure app can be easily removed from existing non-SODAR sites if installed
- [x] Remove "force disabling of taskflow plugin" from tests
- [x] Update docs

**Comment by mikkonie** [comment]
mentioned in commit 23996ff2bcac832b8c383d3bab5ac3afa1d5d921

**Comment by mikkonie** [comment]
mentioned in commit 50c53ba3218ac278019e63479a99a2ff015621b5

**Comment by mikkonie** [comment]
mentioned in commit b8a65c4150b7c6a88ac8a9ce6cdc60fc4cfa560e

**Comment by mikkonie** [comment]
mentioned in commit 3572f8782a888ec9841950cee4f9cd251abc446f

**Comment by mikkonie** [comment]
marked the task **Replace taskflow calls with a plugin-based API** as completed

**Comment by mikkonie** [comment]
marked the task **Make sure to also remove app from install package!** as completed

**Comment by mikkonie** [comment]
marked the task **Ensure app can be easily removed from existing non-SODAR sites if installed** as completed

**Comment by mikkonie** [comment]
marked the task **Ensure app can be easily removed from existing non-SODAR sites if installed** as incomplete

**Comment by mikkonie** [comment]
mentioned in commit c1c48e10948bf4e2a017a4b2839bf626e5f41355

**Comment by mikkonie** [comment]
mentioned in commit a5b002c17d9f14e2d6b725e6801d6998d1d74948

**Comment by mikkonie** [comment]
mentioned in commit 146f5986a5b6925de94e0aa44e9c756169177c56

**Comment by mikkonie** [comment]
mentioned in commit f7c65b21413c1e35c8d341d28e18b9a9eb4296b6

**Comment by mikkonie** [comment]
mentioned in commit 1b379bc63a27969ad34e09c0280a7691133c5095

**Comment by mikkonie** [comment]
mentioned in commit 086ca69e7c6c8b0a363d6ab35056d40d1b2a20b0

**Comment by mikkonie** [comment]
marked the task **Replace role modifying taskflow calls with a plugin-based API** as completed

**Comment by mikkonie** [comment]
mentioned in commit d98f3378c5a717a78af9f4b7d2ec30c91d11bbbd

**Comment by mikkonie** [comment]
mentioned in commit 667ba596bdddf92e4bb400a70383ead2e14c5fc7

**Comment by mikkonie** [comment]
mentioned in commit c9acb56b45c8d10d4a1bd3ecebcff1ca226b477e

**Comment by mikkonie** [comment]
mentioned in commit 889272e825f36e915073abf6b03cf876b5ac3ef1

**Comment by mikkonie** [comment]
mentioned in commit 3d82c4d4ff9116945dcad14b0fed0e6a14cc5d38

**Comment by mikkonie** [comment]
mentioned in commit 67ea11b47fc67346aebc3fc63e32102e43afdb65

**Comment by mikkonie** [comment]
mentioned in commit dc058cf69582409f941b03490556482046df9881

**Comment by mikkonie** [comment]
mentioned in commit 396f0264fcd2eef8d6ed1378e110e42d78a6795f

**Comment by mikkonie** [comment]
mentioned in commit a253ae6cb7371c1708cd475817178cf1b32d8a49

**Comment by mikkonie** [comment]
mentioned in commit 5cdc6b8857fcf10a824a58f496bbc2a48bd47bc8

**Comment by mikkonie** [comment]
mentioned in commit 6bc539aa7cf371fabb2a5ab103b206756be2f36a

**Comment by mikkonie** [comment]
mentioned in commit f3a83d8db66c9042bcc5f24a14dd3849c7dc5140

**Comment by mikkonie** [comment]
mentioned in commit 0a2ad15aefae6332b2aebe8216fc5b837ef9950f

**Comment by mikkonie** [comment]
mentioned in commit 496b816ae94adf38395e62ddba26b74a3dd47384

**Comment by mikkonie** [comment]
mentioned in commit 3623ffcc25b08bf77c38530e4ef19ac6ea6147ec

**Comment by mikkonie** [comment]
mentioned in commit 02d574509d622b04016d0369605fcec23ef8c36b

**Comment by mikkonie** [comment]
mentioned in commit e2562b20736ed7b845ee93417572215a275bbf21

**Comment by mikkonie** [comment]
mentioned in commit 524fb1d4ab97f8d72785541285c75a8ca47c8870

**Comment by mikkonie** [comment]
mentioned in commit b5b247cb088f83e3e99ffdb15f725f4255ddfdb6

**Comment by mikkonie** [comment]
marked the task **Remove taskflow app** as completed

**Comment by mikkonie** [comment]
marked the task **Move taskflow tests into SODAR** as completed

**Comment by mikkonie** [comment]
~~Something going wrong in `batchupdateroles`, dump~~

Fixed! Just forgot to remove the redundant `sodar_url` arg.

**Comment by mikkonie** [comment]
mentioned in commit 238919d0aba952b993e7d7486176371f5ee4e6b3

**Comment by mikkonie** [comment]
marked the task **Fix `batchupdateroles` (see `projectroles.tests.test_commands.TestBatchUpdateRoles`)** as completed

**Comment by mikkonie** [comment]
marked the task **Remove `sodar_url` from all APIs** as completed

**Comment by mikkonie** [comment]
marked the task **Ensure app can be easily removed from existing non-SODAR sites if installed** as completed

**Comment by mikkonie** [comment]
mentioned in commit 97cfb8cd49a6074a6151dc7cad6b036994c2b9f8

**Comment by mikkonie** [comment]
mentioned in commit 869e9460a1b22075f79d9a16ff984f886c4bb49e

**Comment by mikkonie** [comment]
mentioned in commit 2a8ebada2fd7182518e7cbae4819db02e7f00f0f

**Comment by mikkonie** [comment]
mentioned in commit 03cc64ac46d1cc47dd42e52c8814033c892a2935

**Comment by mikkonie** [comment]
mentioned in commit 44378b087d53339ad8d8a4066f056f0082b771cc

**Comment by mikkonie** [comment]
mentioned in commit 8abffabea57fb7fad269fd77f5ff0acc5a89448e

**Comment by mikkonie** [comment]
mentioned in commit 1c2009283955b70fc5f7afe64bb7d3783bb56cc1

**Comment by mikkonie** [comment]
mentioned in commit b322f6166c328d0f2927cc771eed2d1abf9c3b01

**Comment by mikkonie** [comment]
mentioned in commit 78842fbd5c03fd8f3cce8e746b88e4371c439be4

**Comment by mikkonie** [comment]
mentioned in commit 0fe9a8838ac24eecb4b941731eb4e8cf552e9bda

**Comment by mikkonie** [comment]
mentioned in commit ca1cdab4adfaf41c65524b93593ff2fe94501375

**Comment by mikkonie** [comment]
mentioned in commit b5a9dd3bfea5b92ac4a39576241f3b36df59b0f5

**Comment by mikkonie** [comment]
mentioned in commit 413531f99668877acc1cc0d752499efe741dcf60

**Comment by mikkonie** [comment]
marked the task **Replace invite accept calls with plugin-based API** as completed

**Comment by mikkonie** [comment]
mentioned in commit 6334a78c0febf73c1170096dc0d276b49111cc12

**Comment by mikkonie** [comment]
marked the task **Replace owner transfer calls with plugin-based API** as completed

**Comment by mikkonie** [comment]
marked the task **Implement taskflowbackend in SODAR using the APIs (sodar-server##691)** as completed

**Comment by mikkonie** [comment]
mentioned in commit e7721354ba6ed8499cbe0ca4d4d50f3e8fc35f95

**Comment by mikkonie** [comment]
mentioned in commit d6784028d673de873ce963267865aeedf5860da9

**Comment by mikkonie** [comment]
mentioned in commit 17e0169be4066010c07ec5fd5eeb9057545c54bd

**Comment by mikkonie** [comment]
mentioned in commit f5d99689e7a85f5836459277c456e70dd85b8bb4

**Comment by mikkonie** [comment]
mentioned in commit bca62a929d31e007d40d15647ee84ac23ca576ee

**Comment by mikkonie** [comment]
mentioned in commit a958fb02fd7e92b5e5319394e3889ef3de119f6c

**Comment by mikkonie** [comment]
mentioned in commit 056c6a24379b4930217c3295b9d0b076c040be6d

**Comment by mikkonie** [comment]
mentioned in commit e5316187cf71e41ccba4d23a4b8072d541120b3a

**Comment by mikkonie** [comment]
mentioned in commit 123421896432429ba52ef5250241d690822d9b92

**Comment by mikkonie** [comment]
mentioned in commit 62da942835072e4e4286c5eb999eb5db3a7b68a6

**Comment by mikkonie** [comment]
mentioned in commit 6b10a8a04860c5192a2d0d071d95dd93b0925068

**Comment by mikkonie** [comment]
mentioned in commit 370b4b8a88b0fc2a516b141c0d9e8e2e1df3d2f2

**Comment by mikkonie** [comment]
mentioned in commit f8acdaf2b85930d9e0ee8f4d84ccb155a0d07752

**Comment by mikkonie** [comment]
mentioned in commit 2e697b5a8e810819b971958903f7da098aa88dc6

**Comment by mikkonie** [comment]
mentioned in commit 5718fa8066fd8c01f3ded9c4a6b0338dc851ed18

**Comment by mikkonie** [comment]
mentioned in commit 1715c39a0d503577f40004879bd22d53493c4287

**Comment by mikkonie** [comment]
mentioned in commit efd8966f66a490f76f194298a9a19b9e90c98a7d

**Comment by mikkonie** [comment]
mentioned in commit 4b62782d8290272d356abcc1d9aeace7e5191076

**Comment by mikkonie** [comment]
mentioned in commit 785960dd8660d97a9b3891c2242219d9d59cba6e

**Comment by mikkonie** [comment]
mentioned in commit a457b72895bf215f68f25ff82e8e8f0af12798d3

**Comment by mikkonie** [comment]
mentioned in commit 2f3351587a95ab9a326bae2ff8357dabef3423da

**Comment by mikkonie** [comment]
mentioned in commit f24f7dda714b53411e143c1b1dd558ef311f1daf

**Comment by mikkonie** [comment]
mentioned in commit a3bc4edc02e66fa7035dc7e198853ffd41cd1252

**Comment by mikkonie** [comment]
mentioned in commit 3f0c1e5e0949aea34b3febcaa990b049768a3dfd

**Comment by mikkonie** [comment]
mentioned in commit 58b67846ce2c86b2c89bfc58ed83b84459c10ad6

**Comment by mikkonie** [comment]
mentioned in commit 40d0785bf14e67debadc71df0d7ffed231a481f0

**Comment by mikkonie** [comment]
Done.
