### ISSUE TITLE
Projectroles: Add initial kiosk mode support

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#406]
See Manuel's email and initial patch.

## Tasks
- [x] Apply patch for overriding login requirement
- [x] ~~Allow overriding the home view with a kiosk-friendly version~~ Already done by Manuel's Varfish patch
- [ ] Hide unusde links/features in kiosk mode (where applicable)
    * **TBD:** Which ones to hide?
- [ ] Provide way to return an override URL to redirect requests which are not allowed
    * Just redirect to the home view which can then have internal redirect logic?

**TBD:** More?
