### ISSUE TITLE
Add option to send admin alert as email to users on creation

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#415]
I've occasionally thought this might be useful. Otherwise people might miss e.g. some upcoming downtime just because they haven't logged in right before it.

@holtgrewe, opinions?

**Edit:** After issues such as the iRODS outages, I've received requests for implementing exactly this. Also a lot of users don't log into SODAR regularly but might be simply viewing something through GitHub. Could bump it up to the next version as it's quite simple to do.

I just wonder how the Charité email server likes very large batches of emails. Does this require some special setup on the sender's side?

**Comment by mikkonie** [comment]
There has been a lot of demand for this functionality, so I'm bumping it for v1.0.

I do like the idea for some more generic email/notification framework. It would be also related to controlling email alerts for the appalerts app. However, for now I think it's best to simply implement the adminalerts-specific email sending and get this much-needed feature out of the way. We can specify and implement an generic email alert configuring app later as a more major change and refactor this functionality to work on it.

Spec forthcoming.

**Comment by mikkonie** [comment]
## Spec

- Add field to admin alert form to send email on create/update
    * Default=True if creating alert, False if updating (so we don't create extra spam for e.g. fixing a simple typo)
    * Update field label accoding to creation/update
- Add email setting for the `to` header (defaults to `EMAIL_SENDER`)
- Gather user emails including alt addresses in `bcc`
- Set up a template for admin email
- Add opt-out setting
- Test and document as usual

## Tasks

- [x] Add form field
- [x] Add email template and sending logic
- [x] Add opt-out setting
- [x] Add tests
- [x] Add documentation

**Comment by mikkonie** [comment]
Done.
