### ISSUE TITLE
Adminalerts: Add an "activate/deactivate" link to list buttons

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#42]
Would just be faster than going through the update page.

Not urgent, can be done at the same time as sodar-server##196 and sodar-server##179.

Edit: those are done now so might as well. No need for any javascript bells & whistles for this, just basic Django stuff.

## Tasks
* [x] Add a view for activating/deactivating an alert
  - This should redirect back to the alert list with a Django message once successful
  - Provide alert UUID in the URL regex
* [x] Add button to call such view for each alert in the list
* [x] Add tests for the views (including permission tests)

Most stuff can be copied and renamed from similar existing views, URL configurations etc. in other apps.

Hint: Recommend reviewing the following for implementing views,: https://sodar-core.readthedocs.io/en/v0.6.2/development.html
