### ISSUE TITLE
Cleanup and Refactoring for v0.7.2

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#423]
Minor items for cleanup and refactoring here.

## Tasks

* [x] Remove redundant `has_perm` assignments from projectroles templates (at least `_project_header.html` has these)
* [x] Do #429 
* [x] Add test(s) for `get_project_list_columns()`
* [x] Fully document `project_list_columns` in the docs 
* [x] Add changelog note for #456
* [x] Look into section ordering in `dev_project_app`
