### ISSUE TITLE
Filesfolders: Implement API

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#443]
In GitLab by @holtgrewe on Jan 20, 2020, 11:48

## Tasks for Merging

- [x] Update to use base API view classes and match formatting
- [x] Update view tests to use new base test classes
- [x] Use `SODARUserSerializer` for `owner` fields
- [x] Add permission tests

## Short Specification

DRAFT

- generally, follow the structure existing in SODAR
- in particular
    - API URLs go into the apps, e.g., `filesfolders/api/...`
- deviations:
    - create `ui_urlpatterns` and `api_urlpatterns` in `urls.py` and define `urlpatterns` as concatenation of both
    - put API views into `view_apy.py` next to `views.py`
    - create `serializers.py` next to `views.py`
- we don't need to have the upload ZIP or batch update functionality from the UI views
- we implement "object store" semantics, not file system--like recursive traversal semantics

## API URL list

```
/filesfolders/api ...

/folder/list-create/:project_uuid       -- list / create folders
/folder/view-update/:folder_uuid        -- view / update folder
/file/list-create/:project_uuid         -- list / create files
/file/view-update/:file_uuid            -- view / update file
/file/serve/:file_uuid                  -- access file content
/link/list-create/:project_uuid         -- list / create hyperlinks
/link/view-update/:link_uuid            -- view / update yperlink
```

Also, in listing we support the following query parameters

```
?folder=$folder_uuid                              -- filter within the given folder
?order_by=created|updated|name                    -- order by created, updated date or name
?sort=ascending|descending                        -- order ascendingly/descendingly
```

**Comment by mikkonie** [comment]
unassigned @holtgrewe
