### ISSUE TITLE
Projectroles: Display timeline events for categories

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#447]
## Tasks

- [x] Add `category_enable` to `ProjectAppPlugin` and make project detail page use it
- [x] Setup display for timeline app
- [x] Make sure this also works for sidebar and project dropdown (see #501)
- [x] Update tests
- [x] Document all of the above
