### ISSUE TITLE
Integrate token management app from Varfish

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#452]
Use VarFish API branch, `tokens` app, ask Manuel for pointers.

## Tasks

- [x] Import app from VarFish
- [x] Refactor code to conform to SODAR Core standards
- [x] Refactor URL patterns to conform to SODAR Core standards
- [x] Refactor templates to conform to SODAR Core standards
- [x] Fix clipboard copying
- [x] Use clipboard copying visualization
- [x] Add initial docs
- [x] Fix back link in delete view
- [x] Add mention to app lists in docs
