### ISSUE TITLE
Projectroles: Redesign user autocomplete queryset handling

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#455]
Need to figure out a better example to exclude options from the user autocomplete widget than e.g. having a separate view like `UserAutocompleteExcludeMembersAPIView` for each special case.

Could just provide a list of UUIDs in the querystring? Permissions will be checked in the server anyway.

Related to #440.

## Tasks

- [x] Figure out how to nicely modify queryset from forms
- [x] Refactor existing calls
- [x] Remove unnecessary `UserAutocompleteExcludeMembersAPIView`
- [x] Add helper method for creating the appropriate widget
- [x] ~~Rename API views to conform to common naming~~ Postponed to v0.8.0
- [x] Document all of the above
