### ISSUE TITLE
Projectroles: Enable roles for categories

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#463]
Currently only an owner role can be set for a category. We need category roles to determine access for certain functionality.

Note that this does not explicitly mean inheritance of roles from categories into projects as discussed in #17.

## Tasks

- [x] Remove restrictions for non-owner users in categories
- [x] Ensure roles are not updated in taskflow for categories
- [x] Ensure this works fine with remote project sync (preferable not requiring changes in target!)
- [x] Ensure all tests are updated accordingly
- [x] Update docs regarding these issues
