### ISSUE TITLE
Refactor Ajax views

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#475]
Since I'm refactoring API views in general, this should be done as well.

## Tasks
- [x] Do #465 
- [x] Rename views and URL patterns
- [x] ~~Correct HTTP responses everywhere (no auth = 401, not 403)~~ Err no, actually 403 is correct with session auth
- [x] Limit auth backends to session auth

This should also be done for SODAR, naturally.
