### ISSUE TITLE
Unify SODAR API

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#48]
Working on missing API functionality and reworking the API for SODAR v0.8.

## Tasks

- [x] Copy generic views and serializers from SODAR v0.7.0 (#461, #462)
- [x] Reorganize UI views, API views and Ajax views (naming, locations, urlpatterns) (#480)
- [x] Do initial projectroles API (#450)
- [x] Cleanup and merge filesfolders API (#443)
- [x] Make sure everything is tested
- [x] Document!

## Old Stuff Below

This issue was originally just about API authorization, but I realized this is a good chance to rework the API in general.

For most purposes, there should just be ONE general SODAR API, with different auth schemes for certain cases (Django auth for Ajax views, token management for other stuff, etc).

E.g. we shouldn't have a specific "edit project stuff" API for Taskflow, but instead a general SODAR editing 

API with access given to Taskflow.

Everything should also inherit the same base classes for e.g. versioning and such, where ever applicable.

Currently auth in different API views is very much of a mixed bag, some by design but some not so much:

- Ajax views use Django session auth (this is OK)
- Certain views for non-users use a simple token system (Remote projects, user invites
- Taskflow API views use a simple token system (Taskflow could be integrated into SODAR Core and projects based on it, see #387)
- The proof-of-concept BeLove ID query view uses full-on Knox auth
- Some fallbacks to basic auth are included

This should not be a huge change, as a lot of the stuff is already done in these different API approaches. One bigger thing is to do an improved version of token auth with more variability than the very basic Knox scheme. This will also require many modifications in in sodar and sodar_taskflow, of course.

Relevant issues: #46, #47, #116 

EDIT 2020-01-20: We had a talk with @holtgrewe and agreed on the following:

- Initially use Knox auth for per-user API views
    * Later on expand to include project-based permissions
- Upgrades to system level API are **TBD**
- Initially, change remote sync API to use tokens in headers instead of query string
- See base API classes, update where necessary (e.g. version)
