### ISSUE TITLE
Cleanup and Refactoring for v0.8.0

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#485]
The usual story, adding minor things here to be done right before freezing the release.

## Tasks

- [x] Document API views
- [x] Change current API docs into "Django API documentation"
- [x] Make sure `instance` naming is consistent within custom UI/API modification methods
- [x] Remove `cleanup_data` from `assert_response_api()`, use `cleanup_method` instead
- [x] Ensure logical (and non-overlong) names for base API view classes
- [x] Remove `login_knox()` (no longer needed)
- [x] Remove `SheetSubmitAPIView`
- [x] Allow old API versions to prevent remote sync API from breaking
- [x] Ensure `reverse()` is consistently imported
- [x] Ensure `delete` and `destroy` are consistently used
- [x] Try to make `test_widget_user_options` work more consistently (#253)
- [x] Document base API views, core API views and base Ajax views
- [x] Add "Known Issues" section in Major Changes doc (1)
- [x] Remove references to Python 3.8 in docs, contributing etc. (2)
- [x] Rename `ex_owner_role` to `old_owner_role` for consistency
- [x] Document the `PROJECTROLES_TEST_UI_*` settings!
- [x] Use consistent kwarg order in `_make_assignment_taskflow()`
- [x] Use new base classes in `projectroles.forms` throughout the project
- [x] Document new base classes in `projectroles.forms`
- [x] Cleanup `UserAutocompleteRedirectAjaxView`
- [x] Unify assignment naming in tests (e.g. `as_owner` vs `owner_as`)
- [x] Test `test_api_versioning*` with a more simple API view (see comments)
- [x] Document reusable serializers

## Notes

- (1) Add note about category roles beyond owner not synced in this version and project app settings not yet manageable via API
- (2) This project does not (at least yet) support anything above Python 3.6 and Django 1.11 does NOT support Python 3.8!
