### ISSUE TITLE
Projectroles: Minor API issues

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#489]
Personal note for some stuff while I'm doing other stuff.

## Tasks

- [x] ~~Proper `Project.readme` serialization~~ Postponing into a separate issue (1)
- [x] ~~Project creation serialization not returning `roles` or `submit_status` at the moment (2)~~ This is actually a DRF feature
- [x] Do not allow `Project.type` change on update
- [x] Refactor parent providing on create (3)
- [x] Add a specific base serializer based on `SODARModelSerializer` with a predefined `project` field (4)
- [x] Ensure user perms for project parent
- [x] ~~Use ``TestPermissionMixin`` instead of ``TestPermissionBase``~~ Cancelled (see #490)
- [x] Force returning of `sodar_uuid` on creation? (Is this possible?)
- [x] Make `sodar_uuid` the default lookup field instead of `project__sodar_uuid`

## Notes

- (1) How to set up `project.readme` serialization to/from the `raw` member without the cheaty replacement in `to_representation()?`
- (2) Not critical, but it would be nice and logical if the output matched between creation/update.
- (3) Should be a parameter to also work nicely on update. Need to also refactor permission checking.
- (4) This would allow us to specify sodar_uuid lookup and queryset without the user having to do it.
