### ISSUE TITLE
Re-implement remote project sync API view

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#491]
Now that we will finally have a proper API definition in the works, this functionality should be completely refactored. Needless to say, this will be extremely breaking.

## Tasks

- [ ] Make compatible with serialized DRF views where applicable (1)
- [ ] Use standard base views
- [ ] Replace arbitrary token with system user access
- [ ] Make sure url config, view responses etc. correspond to DRF API views

## Notes

- (1) Since handling nested serializers is wonky in DRF we might not be able to implement this (at least entirely) using basic serializers. We should still try to make the input/output as close as possible.
