### ISSUE TITLE
Standardize sodarcache API views

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#498]
Updated for v1.0.

## Tasks

- [x] Add serializer
- [x] Add v1.0 versioning
- [x] Update retrieval view
- [x] Update date retrieval view
- [x] Update create/update view
- [x] Update tests
- [x] Add permission tests
- [x] Update docstrings
- [x] Add API docs
- [x] Add breaking change doc

**Comment by mikkonie** [comment]
Done.
