### ISSUE TITLE
Projectroles: Add non-owner category users to remote project sync

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#502]
Previously, we only had owner level members for categories. This was changed for v0.8.0, where other member levels could be added with the ability to e.g. create projects under the category.

We should change this so that we sync all available roles for categories to target sites, not just owners.

There isn't a specific use case for this at the moment, but at least this would make category details visible for their members also on target sites.

This should not break compatibility with previous API versions, as the data structure remains the same. If it does we can just bump the minimum remote sync API version requirement to 0.9.

**Hint:** See row `1015` of `remote_projects.py` for the current code :)

## Tasks

- [x] Sync all members for categories to TARGET sites
- [x] Make sure these are also correctly displayed in the UI
- [ ] Update tests to ensure this works as expected
- [ ] Update docs where applicable

**Comment by mikkonie** [comment]
unassigned @stolpeo
