### ISSUE TITLE
Add custom Django checks for site startup

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#504]
Adding this as a reminder, to be worked out in detail.

Since Django provides hooks for doing your own custom checks when starting up the server, why not use these so we catch issues before they occur in random usage? (e.g. the email server problem we just had this week)

A similar thing should be done for SODAR as well for relevant stuff (iRODS etc)

## Tasks/Ideas

- [ ] Verify existence of mandatory Django settings variables
- [ ] If email is enabled, check to see if we can reach the email server
- [ ] Verify validity of app settings definitions

**Comment by mikkonie** [comment]
Closing this issue in favour of more specific ones to be raised when we need specific checks. The basic scaffolding for projectroles checks is now available in `projectroles.checks`.
