### ISSUE TITLE
Projectroles: Make category owner transfer work similarly to projects

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#508]
Needed for #464 and is also logical because we allow role management for categories now.

## Tasks

- [x] Allow transferring role in member management
- [x] Remove owner update from project update form
- [x] Prevent owner update in project API serializer
