### ISSUE TITLE
Projectroles: Add moving of projects between categories

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#512]
This was discussed a little when talking about the category rights changes (#464). After making those changes, implementing this functionality should be very straightforward.

**EDIT:** I tested and remote sync for these changes also works without needs for change, with one cosmetic issue which can be postponed to v0.9.0. This means I can bump this feature up to v0.8 and implement immediately.

## Tasks

- [x] Add parent widget to category/project updating, with valid choices (1)
- [x] Implement similar functionality in API view
- [x] ~~Update remote sync as needed~~ see #513
- [x] Make sure everything works with Taskflow (2)
- [x] Update tests
- [x] Document

## Temp Tasks
- [x] Fix project moving if `parent=None`
- [x] Fix currently failing tests
- [x] Fix parent uuid updating with taskflow
- [x] Fix removal of no longer valid inherited assignments with taskflow
- [x] Fix "project created" email to inherited owners when moving a project (should say "moved")
- [x] Simplify `modify_project()` to get rid of Flake8 complaint
- [x] Make sure empty parent choice always shows up and is valid, if it is the current parent
- [x] Ensure moving a category under its children is properly forbidden both in UI and API

## Notes

- (1) Required permissions
  * User moving a project must be the owner (or an inherited owner) of the project being moved
  * User moving a project must have at least contributor permissions to the target category
- Other validation
  * Project with the same title can't exist inside target category
  * Only superuser can move category to root
  * Projects can't be moved to root (naturally)
- (2) For Taskflow this should require no changes apart from updating inherited owners, as projects are maintained in a flat hierarchy in iRODS
