### ISSUE TITLE
Add app settings management to REST API

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#521]
This wasn't a part of the requirements for the original REST API tasks, so it was left for later. I have received requests for adding this and since the API will be updated in v0.12 anyway, this seems like a good time to do it.

The API should use and follow the internal `AppSettingAPI` where applicable, with appropriate permission checking of course. This should be mostly straightforward to implement, writing tests will be the biggest time sink.

## Tasks

- [x] Add API views
- [x] Add serializer for `AppSetting` (only for retrieval)
- [x] Handle project settings update in project modify API
- [x] Add tests
- [x] Update docs

**Comment by mikkonie** [comment]
Done. I did not implement API views for listing settings, as I don't see a use case for that. If one arises, they can be added later.
