### ISSUE TITLE
Cleanup and Documentation for v0.8.1 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#528]
## Tasks

- [x] Cleanup docstrings in `projectroles.serializers`
- [x] Update header references in REST API docs (see related docs in the latest SODAR release)
- [x] Do #526 
- [x] Add 0.8.1 to allowed API versions (do not remove existing ones)
- [x] Cleanup the `select2-container` syntax in `projectroles.css`
