### ISSUE TITLE
Projectroles: Allow restricting access to projects by client IP

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#531]
In GitLab by @holtgrewe on Apr 27, 2020, 14:30

Add two app settings with the `PROJECT` scope in the projectroles app to allowlist specific IPs (e.g., list of strings with IP addresses)

Requires #532, should be done together with #533.

These settings are global, so `local` should be set to `False` and this should be mirrored to target sites (see #533).

## Tasks

- [x] Implement projectroles app settings (#532)
- [x] Add boolean app setting `ip_restrict` for enabling/disabling IP-based access (default=False)
- [x] Add JSON setting `ip_allowlist` for a list of allowlisted IP addresses (default = empty list)
- [x] Implement allowlist check for UI/Ajax views in `projectroles.views.ProjectPermissionMixin`
- [x] Implement allowlist check for API views in `projectroles.views_api.SODARAPIProjectPermission`
- [x] Add tests for both a UI view and an API view
- [x] Implement remote mirroring of projectroles app settings (#533)
- [x] Also test the setting as a `TARGET` site
- [x] Update documentation

## Notes

- If `ip_restrict` is `True` but `ip_allowlist` is an empty list, prevent all access
- IP address/network checks can be implemented by [ipaddress](https://docs.python.org/3/library/ipaddress.html)
- Where to get client IP from:
    - In case of no reverse proxy: take from HTTP header
    - Otherwise, try the standard/non-standard ones shown here:
        - https://serverfault.com/a/920060/103467
