### ISSUE TITLE
Projectroles: Enable app settings for the projectroles app

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#532]
Currently, SODAR Core apps can define app settings in their `plugin` module.

We now have a use case (#531) where we would have use for an app setting for project management, which of course should fall under this app.

The catch? The projectroles app does not have its own `ProjectAppPlugin` because it&#39;s the "master" app which defines this plugin point. So we must do it elsewhere.

## Plan

- Define a dictionary with syntax corresponding to `ProjectAppPluginPoint.app_settings` in `projectroles.app_settings`
    * Include the setting needed for issue #531 as the initial setting
- Update `AppSettingAPI` to support projectroles settings
    * If `app_name=='projectroles'`, get setting definition from the root of `app_settings` instead of a plugin
- Make sure projectroles settings are included in relevant forms along with the settings from app plugins which are currently already there
    * `PROJECT` scope settings in `projectroles.forms.ProjectForm`
       + For this we can test against the setting needed for #531 
    * `USER` scope settings in `userprofile.forms.UserSettingsForm`
       + We don't have a use case for a `USER` setting in projectroles at this point, but in a unit test you can use `@override_settings` and create a dummy setting to test
- Add a `local` flag to the app setting definition (ONLY for projectroles)
    * If `True`, display in the project/user update form on a target form and thus allow editing
    * If `False`, do not display on target site forms

## Tasks

- [x] Define projectroles settings in `projectroles/app_settings.py`
- [x] Update `AppSettingAPI` to support projectroles settings 
- [x] Include `PROJECT` scope settings in `projectroles.forms.ProjectForm`
- [x] Include the `USER` scope settings in `userprofile.forms.UserSettingsForm`
- [x] Add `local` flag and form behaviour
- [ ] Implement the example project setting needed for #531 
- [x] Update tests
- [x] Update app settings documentation
