### ISSUE TITLE
Projectroles: Add mirroring of projectroles app settings to remote sites

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#533]
Required for #531, requires #532.

We now have a use case (#531) for mirroring certain project app settings to remote sites.

For now, let's just mirror `projectroles` app settings (once implemented in #532) as these contain the critical functionality we need at the moment. The `projectroles` app is the only app guaranteed to be active on a target site anyway.

If the `local` flag of the setting is `True`, ONLY set this once on a target site when first syncing a remote project.

## Tasks

- [x] Add projectroles app settings data to `get_target_data()` in `projectroles.remote_projects` (1)
- [x] Add populating the received app settings on the target site in `sync_source_data()`
- [x] Prevent editing the mirrored app settings on the target site forms (2)
- [x] Test all of the above (as both `SOURCE` and `TARGET` site!)
- [x] Document the update where relevant

## Notes

- (1): Only data with the scope of `PROJECT` and `PROJECT_USER`, of course
- (2) : Editing other app settings on the target site should still be allowed

This may somewhat overlap with #491, but since that mostly deals with permissions and access management, it shouldn't be a big deal.

**Comment by mikkonie** [comment]
unassigned @stolpeo
