### ISSUE TITLE
Projectroles: Inherited owner can't be made the owner of a subproject

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#534]
Not intentional of course, will fix. Happens both in UI and the REST API.

## Tasks

- [x] Allow transferring role to inherited owner in REST API
- [x] Provide inherited owner as option for role transfer in UI
- [x] Make sure all of the above is tested
