### ISSUE TITLE
Switch from Font Awesome to Material Design Icons

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#54]
Was: "Upgrade Font Awesome".

Looking at FA5/6 they are quite restrictive unless you get a commercial license. @holtgrewe suggested we'd go with MDI instead. I fully agree.

Probably should ue [SVG](https://dev.materialdesignicons.com/guide/iconify) via [django-iconify](https://pypi.org/project/django-iconify/). Will look further into this once I'm done with #194.

## Tasks

- [x] Set up django-iconify
- [x] Set up JSON collection
- [x] Implement spin in CSS
- [x] Update icons in project
- [x] Add management command for downloading JSON collection(s)
- [x] ~~Add tests for management command~~ see #655
- [x] Handle icon replacing (see "star" feature)
- [x] Ignore local collection in git
- [x] Set up icon retrieval in CI
- [x] Remove Font Awesome
- [x] Update docs

## Recommended Icon Replacements
```
fa-check                 mdi:check-bold
fa-clipboard             mdi:clipboard-text-multiple-outline
fa-cog                   mdi:cog
fa-cogs                  mdi:cogs
fa-exclamation-triangle  mdi:alert
fa-plus                  mdi:plus-thick
fa-times                 mdi:close-thick
fa-user                  mdi:account
```
