### ISSUE TITLE
Projectroles: Allow modifying local app settings on target sites

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#545]
In GitLab by @holtgrewe on May 26, 2020, 20:21

**The problem**

- Target site app (VarFish) defines project settings (for assigning tags to cases).
- Project settings for projects in target mode cannot be edited.
- There currently is no way to edit the settings in the source app (SODAR).
- Effectively, the project settings cannot be edited and tags cannot be defined.

**Resolution**

- Allow editing of app settings of local apps on a target site.

**Spec**

- App settings are managed via the project creation/updating form
    * For remote projects on target sites, access to the form is prohibited from all users
- Solution: Make update project form available for remote projects on target site
    * ONLY display the local app settings (NOT projectroles settings once #532 and #533 are implemented!)
    * Handle form submission without the invisible fields present
    * Easiest way is most likely simply to set widgets of the unmodifiable fields hidden and pass the values as usual

**Tasks**

- [x] Allow project update form to be viewed for projects on a target site (by users with appropriate perms)
- [x] Hide widgets for everything except local app settings
- [x] Add tests (as a target site)
- [ ] Optional: if the changes make the form class too convoluted, maybe see about refactoring it?
- [x] Update documentation related to this

Related to #532 and #533, should be done for the same release.

**Comment by mikkonie** [comment]
unassigned @stolpeo
