### ISSUE TITLE
Use type hints where applicable

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#568]
Something I've been thinking about for a while. Type annotations are useful. Alas, they should be used (with a consistent policy) in the *entire* project or not at all, otherwise it will just get mega confusing.

Hence, the whole project (where applicable) should be converted into using these at once. Milestone v0.10 would be a good place to do this as a lot will change at that point anyway.

How to do this? Full annotation for everything? APIs only? How about overridden Django methods? (They'll have an identical signature anyway so seems kind of overkill..)

Should probably look into best practices and how others have handled this in Django projects. Comments welcome.

**Update:** Starting with the straightforward stuff and seeing how far we get.

## Tasks

- [x] Update app APIs
- [x] Update custom model methods
- [x] Update utils methods
- [x] Update plugin methods
- [x] Update view helper methods
- [x] Update form helper methods
- [x] Update test helper methods
- [x] Update template tags
- [x] Review and ensure proper use of `Optional` vs `Union[xxx, None]`
- [x] Review and ensure UUIDs are properly set as `Union[str, UUID]`
- [x] Update docs

**Comment by mikkonie** [comment]
Done. I skipped the standard inherited methods from Django/DRF/etc, as annotating those seems totally redundant. If I missed something I'll add it in a release cleanup commit.
