### ISSUE TITLE
Projectroles: Add public read access support for projects

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#574]
**NOTE:** This is under work after I learned the requirements have changed.

Implement setting project public, to be viewed (but not edited) by anyone, **including unauthorized users**.

## Tasks

- [x] Implement public guest access for authenticated users
- [x] Enable public guest access for anonymous users
- [x] Update base templates and project list
- [x] Test REST API views
- [x] Test Ajax API views
- [x] Make sure to test project list visibility

## Temp Tasks / Reminders

- [x] Fix ALL predicates to support anonymous users
- [x] Hide "starred" button in project list if user is not authenticated
- [x] Add tests for anonymous users
- [x] Display site apps to anonymous users
- [x] Enable search for anonymous users?

## Spec
- Add `projectroles` app setting `public_guest_access`
    * `scope=PROJECT`
    * `type=boolean` 
    * `default=false`
    * `local=true` (needs to be explicitly allowed on target sites!)
- IF setting is True
    * Display project in project list for everybody
    * Allow guest access to project read-only views for all users
- Providing access
    * *Might* be doable by simply checking for the setting in the `is_project_guest()` predicate?
        + If setting is True, also allow action for unauthenticated users
    * `project.has_role()` should also be modified to return True if applies to the project
    * ..but wait! `LoginRequiredMixin` will still cause this to fail :(
        + **TBD:** Create new mixin(s) combining `LoginRequiredMixin` and `LoggedInPermissionMixin` for projects?
        + This might be a good chance to refactor the view mixins in general.. See #468!
- IP restrict and IP lookup settings should override this setting
    * If we use the `is_project_guest()` predicate this should probably happen automatically?
- Visually display public projects, at least for superusers
    * Use `mdi:earth` for public projects, switch to e.g. `mdi:cloud` for remote projects

## Questions/Issues/TBD
- **Q:** In SODAR, how to handle iRODS data access for public users with no "real" role?
    * Normally, we call taskflow to set up group access in iRODS when a user gets membership in project
    * This logic has to go to SODAR, but for now all iRODS project rights handling code is in SODAR Core
    * Hence, this whole task would be better to left done after SODAR Taskflow has been decoupled from SODAR Core..
