### ISSUE TITLE
Cleanup and documentation for v0.8.3 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#579]
Minor things here.

## Tasks

- [x] Cleanup `sodar-code-input` reference in `projectroles.forms`
- [x] Fix `git+https` reference(s) in docs
- [x] Add short guide for setting up remote project sync sites for development in development docs
- [x] Delete alert link in adminalerts missing `text-danger` class
- [x] Fix docstring in `TestAdminAlertPermissions`
- [x] Fix module comments in adminalerts tests
- [x] Fix class inheritance ordering in adminalerts tests
- [x] Fix erroneous `user.is_authenticated()` notation
- [x] Rename `assertEquals()` calls to `assertEqual()`
