### ISSUE TITLE
Projectroles: Disable creating subcategories or projects under a remote category

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#583]
This may result in unwanted operations and messing up sync. Related to #582.

## Tasks

- [x] Update perms to disallow project reation if on a target site and parent is remote
- [x] Hide creation links in UI with the same conditions
- [x] Ensure this also fails in the API if conditions are met
- [x] Update tests
- [x] Update documentation
