### ISSUE TITLE
Projectroles: Add options definition to app settings

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#592]
We should allow an optional list of options for app settings. This would be super useful for sodar-server##995 and most likely there are other use cases to follow. Shouldn't be too much work so let's try to squeeze this into v0.9.

## Spec

- Allow optional options for app settings where the type is either `STRING` or `INTEGER`.
- Define the options as a list under `options` in the settings definition.
- In project and user forms, display widget as `select` with the allowed options if they are present, instead of an input box
- When setting the value directly via API, raise exception if given value is not in defined options
- Validate option type where appropriate, raise exception if incorrect option type is provided in settings definition
    * (Once we do #504, should do validation of app settings definitions directly upon Django startup)

## Tasks
- [x] Add `options` support into `AppSettingAPI`
- [x] Add `options` support into project and user forms
- [x] Add example setting to example app (or add options to an existing example)
- [x] Add tests
- [x] Make sure documentation is up do date

**Comment by mikkonie** [comment]
unassigned @stolpeo
