### ISSUE TITLE
Refactor example PROJECT_USER scope settings

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#599]
A few minor issues I noticed in `example_project_app`:

- Settings should not be called `project_user_*_hidden_setting`
    * `PROJECT_USER` settings are always hidden so the "hidden" part in the name is redundant
    * Thus `project_user_*_hidden_setting` should become `project_user_*_setting`
- `user_modifiable` should not be needed for `PROJECT_USER` settings
    * They are not included in the relevant forms anyway, modification UI must be specifically implemented
    * These should be removed along with making sure everything still works

## Tasks

- [x] Rename relevant example app settings
- [x] Remove `user_modifiable` from relevant example app settings
- [x] Make sure tests still work
- [x] Update docs if applicable
