### ISSUE TITLE
Projectroles: Add batch search

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#609]
Suggested by @holtgrewe.

## Spec

- Add separate view with multi-line text box for including multiple search terms
    * Separate "keywords" box for entire search, at least for now
- Link to this "advanced search" view from site top bar

## Tasks

- [x] Add new search view
- [x] Implement logic for batch search
- [x] Link from base template
- [x] Add tests
- [x] Update search in other app plugins
- [x] Update docs (incl. breaking changes!)
