### ISSUE TITLE
Projectroles: Remove deprecation protection for old style search

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#618]
The old way of implementing plugin search with a single `search_term` is changed for #609. `plugin.search()` now expects a `search_terms` parameter. For now we call the function with a single term if not implemented and produce some warnings if multiple terms are used. This will be removed in v0.10.

## Tasks

- [x] Remove call for legacy `search()` implementation and related warnings
- [x] Remove `context['search_term']`
- [x] Remove template workarounds
- [x] Remove list conversion from `ProjectManager.find()`
- [x] Update docs to notify of breaking change
