### ISSUE TITLE
Extend role inheritance to all roles

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#638]
Requested by @holtgrewe. All roles should automatically inherit but be overrideable with local roles if needed.

## Spec

- Inherit all roles from parents
- Allow overriding role with a local role higher in ranking (see #666)
- Ignore local roles below the inherited one in the ranking hierarchy
- Ignore inherited delegate roles in local delegate limits
- Sync roles appropriately in remote sync

## Tasks

- [x] Update models for inheritance of all roles
- [x] Ensure returning of inherited roles in REST API (#1121)
- [x] Add local role promotion to REST API
- [x] Update UI to display accessed projects correctly
- [x] Update owner transfer in UI
- [x] Update inherited owner promoting in UI
- [x] Update local user demoting prevention in UI
- [x] Add information/warning on inherited/child roles to local member removal
- [x] Add inherited members to API listings
- [x] Ensure email updates are correct for all UI role updates
- [x] Ensure delegate limits for inherited delegates are ignored
- [x] Add checks for local role promotion to owner transfer in UI
- [x] Add checks for local role promotion to owner transfer in REST API
- [x] Ensure REST API works for overridden local role
- [x] Ensure REST API works for owner transfer, test for all combinations
- [x] Handle previously created lower ranking role assignments when promoting
- [x] Update `batchupdateroles` management command
- [x] Update inheritance support in remote sync
- [x] ~~Add and use ranking-based predicates~~ This can be done for #288
- [x] ~~Update permission tests for all apps~~ See #1103
- [x] Update other tests where needed
- [x] Review and update/remove `get_assignment()`
- [x] Ensure category listing for project/category moving works with correct access
- [x] Refactor `get_role()`
- [x] Remove/deprecate unused model helpers and rule predicates
- [ ] Update docs

**Comment by mikkonie** [comment]
Gave up fighting the infinite rebase hell. `feature/full-role-inherit` is the current work branch, `update/role-inherit` is legacy and will be deleted once I'm back up to speed.

Once again, deprioritizing large features like this when they're half-way implemented is a bad idea which wastes time for everybody.

**Comment by mikkonie** [comment]
**Role list controls** with extended inheritance:

- Inherited owner
    * None -> **OK**
- Inherited delegate
    * None -> **OK**
- Local owner
    * See separate comment
- Local delegate
    * Update role
        + Allow promotion or demotion
    * **OK**
- Inherited member
    * Promote user
        + Only allow promoting role
        + **NOTE:** Form should create new `RoleAssignment` OR update existing one, if previously added assignment with lower priority exists
    * **All OK**
- Local member
    * Update role
        + Allow promotion or demotion
        + .. but do NOT allow demotion below inherited role, if it exists
    * Remove member    
    * **All OK**

**TODO:** Add tests for all this

**TODO:** Ensure correct emails are sent for all activity

**Comment by mikkonie** [comment]
Update **role removal** as follows:

- Warn of removing role in child categories/projects if present
- Notify of inherited role still existing if present
- If inherited role is left after removal, notify user of role change instead of removal

**Comment by mikkonie** [comment]
## Owner Transfer

- Old Owner (role is always local)
    * No inheritance -> **OK**
        + Old owner role choices: anything except owner
        + Update local `RoleAssignment`
        + Add alert, send email
    * Inherited role exists -> **OK**
        + Old owner role choices:
            + Anything equal or above inherited role
            + IF role is not owner, THEN exclude owner
        + IF inherited owner is owner, THEN delete local `RoleAssignment`
            + AND do not alert/email
        + ELSE update local `RoleAssignment`
            + AND alert/email
- New owner
    * No inheritance OR both inherited and local role -> **OK**
        + Update local `RoleAssignment`
        + Alert/email
    * Inherited role only -> **OK**
        + Create local owner role
        + IF inherited role is not owner, alert/email

## Misc Issues

- Include all inherited and local non-owners in options -> **OK**

**Comment by mikkonie** [comment]
Done.
