### ISSUE TITLE
Projectroles: Add site-wide app alert plugin and views

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#642]
Requested by @holtgrewe. This is a nice thing and should be quite simple to implement. Need to think of this and write a full spec.

Current idea:

- New type of plugin point for site-wide app alerts, to be implemented in project apps
- Site app plugin for projectroles which gathers data from the plugin and displays it in one view
- Some visible link/icon e.g. in the top bar, when active site-wide alerts exists for the user.

## Tasks

- [x] Add plugin point for site-wide app alerts
- [x] Add site app for app alerts
- [x] Integrate alerts into base template
- [x] New implementation (see below)
- [x] Implement dismiss/redirect
- [x] ~~Include top bar link dynamically~~ Can't get much more dynamic tbh
- [x] Optimize alert layout regarding timestamps etc
- [x] Add model validation
- [x] Add alert functionality for relevant apps
- [x] Add/update tests
- [x] Update docs
