### ISSUE TITLE
Timeline: Add support for events with no project

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#668]
Similar to #119, but without the need for a project.

Not sure if we have a use case currently, but at some point we most definitely will.

This would require adding a site app plugin for displaying non-project-related events.

## Tasks

- [x] Update models
- [x] Update API
- [x] Add site app plugin
- [x] Add site-wide views and templates
- [x] Fix permission check for site-wide view
- [x] Add separate permission for classified site-wide events
- [x] Unify CSS and tour help for templates (see comments in template)
- [x] Add permission, view and UI tests for site-wide views
- [x] Update docs
