### ISSUE TITLE
Icon tweaks for v0.10.0

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#670]
Just writing these down and (preferrably) doing them in one go..

## Tasks

- [x] Use `login-variant` and `logout-variant` instead of `login` and `logout`
- [x] Use `account-multiple` instead of `account-group`
- [x] Use `earth` for public projects, `cloud` for remote projects
