### ISSUE TITLE
Siteinfo: Display relevant Django settings in app

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#671]
Something I thought of a while ago but didn't implement. This would be very useful for admining, as settings could be verified without having to SSH in for env or digging into the Ansible playbooks.

For the projectroles app these could be hard coded. For other apps, should provide a function in the app plugin to provide a list of settings to include.

## Tasks

- [x] Add settings display to layout
- [x] Add core settings
- [x] Add app settings
- [x] ~~Make header sticky~~ Forgot, this doesn't work with tabs nicely
- [x] Add section icons and titles
- [x] Update docs
- [x] Make sure tests pass
