### ISSUE TITLE
Cleanup for v0.10.0 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#682]
Minor tasks here.

## Tasks

- [x] Fix `span` to `i` in major changes icon example
- [x] Fix "projects personnel" typo
- [x] Upgrade minimum Django requirement to latest 3.1.x release
- [x] Fix docstrings in `projectroles.email`
- [x] Add note to breaking changes about replacing `{% load staticfiles %}`
- [x] Increase `spin` CSS speed
- [x] Upgrade `wheel` dependency in CI
- [x] Rephrase issue #699 in changelog
