### ISSUE TITLE
Cleanup for v0.10.1 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#709]
Minor issues here.

## Tasks

- [x] Move PyPI remark in CHANGELOG from v0.10.0 to this release
- [x] Reorganize `.gitignore`
- [x] Update `Makefile` (see sodar_django_site)
- [x] Add `sodar_cache` to default backend plugins in `base.py`
- [x] Update image name comment in `install_os_gitlab.sh`
- [x] Add warning about nesting template blocks in dev docs
- [x] Add note about app setting sync fix requirements in docs
- [x] Add note about `projectroles` vs `projectroles_extend` blocks in app dev docs
