### ISSUE TITLE
Add view to list dismissed app alerts

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#711]
Omitted this from #642 as it's not critical, but after using the feature for a while I realized it would be useful. Should be very quick to implement.

## Spec

- Add "dismissed mode to `AppAlertListView`
    * URL route = `list/dismissed`
- IF we open the view in the dismissed mode
    * THEN modify queryset to return `AppAlert` objects for user where `active=False`
    * AND add context variable specifying the mode, e.g. `context['dismissed'] = True`
    * AND add Django pagination (Note: only if in dismissed mode)
- Modify existing alert_list.html template
    * Change existing page title from "App Alerts" to "Active App Alerts"
    * IF `dismissed`, change title to "Dismissed App Alerts"
    * Replace current "Dismiss All" button with "Alert Operations" dropdown
        + **Hint:** You can copy the base style of this dropdown from existing views and edit that
        + Add option to link to active/dismissed alerts, depending on the current `dismissed` status
        + Add current "Dismiss All" link to dropdown, but only if `not dismissed`
    * Only show the alert buttons div if `not dismissed`
    * Add `_pagination.html` from projectroles if `dismissed`
- **Note:** No fancy sorting or filtering needed for this view, at least for now. It's mostly intended to provide a reference if a user has dismissed stuff and wants to go back to it later.
- Add tests to ensure expected alerts are displayed and buttons are hidden if in dismiss mode
- Update `app_appalerts.rst` in docs to mention the ability to view dismissed alerts under "Usage"

## Tasks

- [ ] Update `AppAlertListView` for dismissed mode
- [ ] Update `alert_list.html` template
- [ ] Add/update tests
- [ ] Update docs

**Comment by mikkonie** [comment]
This was done by @gromdimon last week, forgot to close.
