### ISSUE TITLE
Cleanup code in next major release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#751]
Should do the same thing as I did for SODAR v0.10.0.

## Tasks

- [ ] Unify module import order
- [ ] Remove redundant blank lines
- [ ] Add module descriptions where missing
- [ ] Make sure line length is not exceeded where Black fails to detect it (1)
- [ ] Convert static app JQuery to a more modern syntax and 2-space tabs

## Notes

- (1) Exceptions include test case descriptions and some other stuff where this can't be avoided.

**Comment by mikkonie** [comment]
It seems this is a forgotten old issue which has since already been handled. Closing.
