### ISSUE TITLE
Cleanup for v0.10.3 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#753]
Minor tasks etc etc.

## Tasks

- [x] Do #745 
- [x] Do #752
- [x] Fix double quotes in SAML config
- [x] Fix Django 1.11 doc links in config/settings
- [x] Fix Font Awesome icon references in documentation examples
- [x] Fix changelog entry for #757
