### ISSUE TITLE
Appalerts: Display project name/link in alert as separate element

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#790]
This would spare us the trouble of adding the project title in the alert description and also make things more structured/readable.

## Tasks

- [x] Add project/category badge in alert
- [x] Handle long project names
- [x] Tweak layout for columns
- [x] Remove unnecessary "in project x" text from alert labels

**Comment by mikkonie** [comment]
mentioned in commit f5a7e246b05181df39f1e6b51c7a9bd74c5045b9

**Comment by mikkonie** [comment]
marked the task **Add project/category badge in alert** as completed

**Comment by mikkonie** [comment]
marked the task **Handle long project names** as completed

**Comment by mikkonie** [comment]
mentioned in commit 63ebfcb588126ee65d2d4010abf5556102fca85d

**Comment by mikkonie** [comment]
marked the task **Tweak layout for columns** as completed

**Comment by mikkonie** [comment]
mentioned in commit c40adc396cd2a37f53726e7040f228b7682018e4

**Comment by mikkonie** [comment]
mentioned in commit 7d56f72355f29852b9f400af31897e72759e679f

**Comment by mikkonie** [comment]
mentioned in commit 30ff972eb24bf79bc9d99e6f0ade1d2af3486b3e

**Comment by mikkonie** [comment]
marked the task **Remove unnecessary "in project x" text from alert labels** as completed

**Comment by mikkonie** [comment]
Done.
