### ISSUE TITLE
Cleanup for v0.10.5 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#797]
Minor tasks here.

## Tasks

- [x] Fix `RoleAssignmentCreateView` docstring
- [x] Update all `*@bihealth.de` emails
- [x] Ensure app settings remote sync documentation is up to date
- [x] Cleanup projectroles template tags

**Comment by mikkonie** [comment]
To find the emails use `grep -nir "bihealth\.de" --exclude-dir ".git" --exclude-dir "build" --exclude-dir "node_modules"`

**Comment by mikkonie** [comment]
marked the task **Cleanup projectroles template tags** as completed

**Comment by mikkonie** [comment]
marked the task **Update all `*@bihealth.de` emails** as completed

**Comment by mikkonie** [comment]
marked the task **Fix `RoleAssignmentCreateView` docstring** as completed

**Comment by mikkonie** [comment]
marked the task **Ensure app settings remote sync documentation is up to date** as completed

**Comment by mikkonie** [comment]
mentioned in commit 09952c2404a69fa59e1cf3c9d6c7fd3de78adcab

**Comment by mikkonie** [comment]
Done.
