### ISSUE TITLE
Allow setting former owner role in ownership transfer to "no role"

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#836]
Currently, we require a new role to be set for the former owner when transferring ownershp. However, there are many cases where one doesn't want to assign the former owner any role. In these cases they must first assign a new role to the previous owner and then remove it. This doesn't make sense.

Requires #638 and #1011 (latter mostly to avoid merge conflicts)

## Spec

- Add "No Role" option for old owner in ownership transfer form
- IF "No Role" is selected, remove local role for old owner
- IF role was removed AND inherited role exists for old owner, add alert & send email for "role_update" to inherited role
- ELSE IF role was removed AND no inherited role exists, add alert & send email for "role_delete"
- Add the aforementioned logic to ownership transfer view in REST API

## Tasks

- [x] Add "remove role" support in form and UI view
- [x] Update alerts and email sending in UI view
- [x] Update UI view tests
- [x] Ensure support for no old role in REST API view
- [x] Update REST API view tests
- [x] Update docs

**Comment by mikkonie** [comment]
Placing this in v0.12.0 as it also involves role management.

**Comment by mikkonie** [comment]
~~This requires some breaking changes in `ProjectModifyPluginMixin`, so it should be documented as such.~~ Already done in #1391.

**Comment by mikkonie** [comment]
Done.
