### ISSUE TITLE
Cleanup for v0.10.6 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#842]
Minor tasks here.

## Tasks

- [x] Add note about different base testing classes to dev_general / Testing
- [x] Fix titles and grammar in welcome doc
- [x] Improve "no alerts" message in appalerts UI
- [x] Move constant from the middle of ``projectroles.tests.test_views``
- [x] Move IP allowing tests in ``project.tests.test_views_api`` to bottom of module

**Comment by mikkonie** [comment]
marked the task **Improve "no alerts" message in appalerts UI** as completed

**Comment by mikkonie** [comment]
marked the task **Move constant from the middle of ``projectroles.tests.test_views``** as completed

**Comment by mikkonie** [comment]
marked the task **Move IP allowing tests in ``project.tests.test_views_api`` to bottom of module** as completed

**Comment by mikkonie** [comment]
marked the task **Add note about different base testing classes to dev_general / Testing** as completed

**Comment by mikkonie** [comment]
marked the task **Fix titles and grammar in welcome doc** as completed

**Comment by mikkonie** [comment]
Done.

**Comment by mikkonie** [comment]
mentioned in commit b6445095dcd11b9a3e2af569529285b81443a7fd
