### ISSUE TITLE
Add plugin hook for validating project update form for app settings

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#860]
There are a few cases in SODAR where we would need to do some more complex validation for user-provided app settings, for example bihealth/sodar-server#1310. Also, in some cases we might have other special rules for e.g. syntax and project context, which can't be represented by the setting definition dict alone.

To tackle such issues, we should add a method to project app plugins for validating app settings in the project update form. The method would receive all the settings of that particular app and return errors for individual settings if found.

## Spec

- Add skeleton and docstring of `validate_form_app_settings()` method to `ProjectAppPluginPoint`
    * Args:
        + `project` (`Project` object or `None`)
        + `user` (`User` object or `None`)
        + `app_settings` (dict in format of {'setting_name': 'value')
     * Return value = dict in format of `{'setting_name': 'Error string' or None}`
         + The skeleton should simply return `None` to signify "not implemented"
- Add similar method skeleton to `SiteAppPluginPoint`
    * Same signature *without* the `project` arg
- In `ProjectForm` and `UserForm`, call validation
    * Within `clean()`
    * Call method in each plugin per app, only provide the app's own settings to the method
    * If the method returns `None`, the app's settings are considered to be OK
    * IF setting name is found in return dict and the error value is not `None`, THEN add error to form errors for the related field
- Add example implementation of method to `example_project_app`
    * For both `PROJECT` and `USER` scopes (`PROJECT_USER` is exempt here as those are not included in forms)
- Add tests where these pass/fail
- Update docs where applicable

## Tasks

- [x] Add method skeletons to be implemented
- [x] Add usage in forms
- [x] Add example implementation
- [x] Add tests where example implementation passes/fails
- [ ] Update docs

**Comment by mikkonie** [comment]
mentioned in issue sodar-server##1384

**Comment by mikkonie** [comment]
Done by @gromdimon
