### ISSUE TITLE
Add admin site view to browse all timeline events

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#873]
I've had multiple cases recently where it would be useful for an admin to see a list of all most recent events on the site, regardless of the project (or no project relation). These can of course query for these in the Django shell, but quickly viewing them in the UI would be much better for e.g. urgent debugging.

This is to be a separate list from the "site-wide events" list, as that is also available for regular users and only lists events not associated with a project.

**NOTE:** This is for v0.12.0, so base on `dev` branch.

## Spec

- Add new admin-only view for *all* events
    * Include both project events and site-wide events
    * Including classified events, admin can access those
- Add new `SiteAppPlugin` for this view
    * Call it `timeline_site_admin`
- Add perms in `rules` for seeing all events, requires `is_superuser`
- Create a template for the list
    * Hint: Copy `timeline_site.html` to get started
    * Reuse as much of existing templtes as possible
    * **BONUS:** Unify the template with `timeline_site.html`
- Add project information to the list
    * Display project link when the `ProjectEvent` object actually has an associated project
    * Should not be visible in the existing lists, if reusing `_list_header.html` and `_list_item.html`
    * **TBD:** How to nicely display this without taking up too much screen real-estate?
        + Instead of a separate column, maybe add the project title in the beginning of  the description field
        + We could use a project title badge similar to the `appalerts` app
        + [See here](https://github.com/bihealth/sodar-core/blob/dev/appalerts/templates/appalerts/alert_list.html#L60)

## Tasks

- [x] Add admin view for all events
- [x] Create a new `SiteAppPlugin`
- [x] Set up template(s) to display results
- [x] ~~Add new column for projects to this list~~ We used a badge instead
- [x] Add tests
- [ ] Update docs

**Comment by mikkonie** [comment]
Bumping this to v0.12, as I've recently had need for this feature several times when debugging something and it's tedious to be writing/pasting shell commands all the time..

**Comment by mikkonie** [comment]
Done by @gromdimon, closing.
