### ISSUE TITLE
Add verification and management of additional user email addresses

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#874]
There is a potential problem with the recently introduced (and VERY quickly implemented) additional email field. Right now, the user is able to enter any emails into the "additional email" field with no confirmation. This means that a user would be able to set up "spam" for multiple other people without their consent. Also, typos can lead to the wrong people receiving unsolicited mail. As someone with a 5-character gmail user name I know this all too well ;)

This is a major issue especially as we work on federated access for SODAR. There'll both be more need for the feature and more chance of abuse and mistakes.

I've thought about this for a while. I believe that 1) verification is best practice above opt-out, and 2) managing this in a comma-separated string app setting and some hidden verification app settings would get real clunky real fast. Thus, I believe the solution best combining robustness and bang-for-your-buck would be the following.

## Spec

- Add Django model for alternate emails
    * Add fields for "verified" and "secret"
- Add simple UI for adding/removing emails in the userprofile app
    * Disable UI on target sites
- Send verification mail with secret for each email added
    * Include link for verifying the email, containing the secret
- Add migration to move current app setting alt emails to model
- Add model to remote sync
- Add model to REST API user views
- Remove old app setting

## Tasks

- [x] Add model
- [x] Update usage in email sending
- [x] Add UI
- [x] Add verify view
- [x] Add migration
- [x] Add model to remote sync
- [x] Add model to REST API
- [x] Add tests
- [x] Document

**Comment by mikkonie** [comment]
This was done a while ago, it seems the ticket was accidentally left open.
