### ISSUE TITLE
Upgrade to Django v4.2

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#880]
Django v4.0 is out since December 2021. SODAR Core v1.0 would be the prime candidate for this dependency bump.

Need to see if there are any issues in SODAR, Varfish, Kiosc et al. potentially preventing this upgrade. Feedback is welcome from @holtgrewe, @stolpeo etc.

**Update 2024-01:** Django 5.0 is out since December 2023. However, 4.2 is a stable LTS release and I firmly believe we should go with that instead at this point in time.

Requires #1074 (see notes).

## Dependency Issues

- [x] Update `django-plugins-bihealth` for Django 4.2 support (see bihealth/django-plugins#10)
- [x] Update `drf-keyed-list-bihealth` for Django 4.2 support (see bihealth/drf-keyed-list#6)
- [ ] ~~Switch from `django-saml2-auth-ai` to a maintained SAML package (see #597)~~ Remove SAML support (see #1368) (4)
- [x] Update `django-plugins-bihealth` dependency into a PyPI release (9)
- [x] Update `drf-keyed-list-bihealth` dependency into a PyPI release (10)
- [x] Update [django-db-file-storage](https://github.com/victor-o-silva/db_file_storage) dependency into a PyPI release (5)
- [x] Upgrade to PostgreSQL >11 (#1074)
- [x] Update version number mentions in Django config

## Internal Issues

- [x] Replace `django.utils.translation.ugettext_lazy` imports with `gettext_lazy`
- [x] Replace `django.conf.urls.url` imports with `django.urls.re_path`
- [x] Fix `BaseForm.__init__()` issues in `TestRoleAssignmentDeleteView` (6)
- [x] Fix `RemoteSiteDeleteView` post handling
- [x] Fix primary key issue in `Project.save()` (7)
- [x] Fix primary key issue in `projectroles.forms` line 700 (8)

## Cleanup

- [x] Add #880 to changelog
- [x] Add #1157 to changelog
- [x] Update docs regarding Django version requirements
- [x] Update docs regarding Python version support and 3.11 recommendation

## Notes

1. ~~Django v4.x drops support for Python <3.8, which means we should too.~~ Already done!
2. The release contains breaking changes as well as deprecated and removed features. [See release notes here](https://docs.djangoproject.com/en/4.0/releases/4.0/).
3. Support for Postgres v11 has been dropped in Django v4.2. This means we'll have to upgrade the minimum version used.
    * I had some problems when I attempted an upgrade in sodar-docker-compose. I need to ensure the upgrade can be done without problems. This might just be fixed by deleting existing cache, but we'll see..
4. SAML support can be removed, see #1368.
5. **UPDATE:** Now actively maintained and a new version has been tagged! Woop!
6. It seems Django <4 didn't care about extra form kwargs and would just ignore them if not explicitly set in the form init. I had redundantly included `CurrentUserFormMixin` to this view and before it simply affected nothing.
7. This raises the error `'Project' instance needs to have a primary key value before this relationship can be used.` in Django 4.1. Will probably have to do `super().save(commit=False)` first.
8. Seems to be the same problem as in (7).
9. Automated PyPI release process not working.
10. Pending review of PR and PyPI release.

**Comment by mikkonie** [comment]
FYI: At the time of writing, I'm holding off from merging this into dev. This is because I realized that in order to get the SODAR dev env working for Postgres v12+, I need to do bihealth/irods-docker#16, bihealth/irods-docker#17 and bihealth/irods-docker#18.

Why? because I'm lazy and don't want to maintain separate docker compose dev envs for SODAR and SODAR Core :P

If I get more resources working on SODAR Core v1.0 tickets before finishing the aforementioned tasks, I'll bite the bullet, merge this and set up separate dev environments for myself..

**Comment by mikkonie** [comment]
Done.
