### ISSUE TITLE
Upgrade Python dependencies

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#884]
I haven't done this in a while. Also, I got a dependapot alert for celery so that should definitely be bumped up. Also shouldn't forget #879.

## Tasks

- [x] Upgrade and test standard dependencies
- [x] Upgrade sphinx dependencies and ensure the RTD theme still works
- [x] Upgrade versioneer and replace versioneer.py file
- [x] Updgrade and test test requirements
- [x] Update deprecated selenium calls, add to documentation

**Comment by mikkonie** [comment]
marked the task **Upgrade and test standard dependencies** as completed

**Comment by mikkonie** [comment]
marked the task **Upgrade sphinx dependencies and ensure the RTD theme still works** as completed

**Comment by mikkonie** [comment]
marked the task **Upgrade versioneer and replace versioneer.py file** as completed

**Comment by mikkonie** [comment]
marked the task **Updgrade and test test requirements** as completed

**Comment by mikkonie** [comment]
marked the task **Update deprecated selenium calls, add to documentation** as completed

**Comment by mikkonie** [comment]
Done.

**Comment by mikkonie** [comment]
mentioned in commit f0af07e5b5c08cf7bf27114ec91be3f6e2afa10f

**Comment by mikkonie** [comment]
mentioned in commit 5ffc1c1b1ea7807793f54b1dca65dca340bf8e9c

**Comment by mikkonie** [comment]
mentioned in commit sodar@6a27f30bf374801114ad5c32a64a06d746d19e44
