### ISSUE TITLE
Cleanup for v0.10.8 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#892]
Minor tasks here.

## Tasks

- [x] Update timeline UI screenshot
- [x] Fix unused variable in `for i in range(5):`
- [x] Add blank line in `timeline.css` before `.table#sodar-tl-table thead tr th:nth-child(3),`
- [x] Add wheel to `install_python_dependencies.sh`

**Comment by mikkonie** [comment]
marked the task **Fix unused variable in `for i in range(5):`** as completed

**Comment by mikkonie** [comment]
marked the task **Add blank line in `timeline.css` before `.table#sodar-tl-table thead tr th:nth-child(3),`** as completed

**Comment by mikkonie** [comment]
marked the task **Add wheel to `install_python_dependencies.sh`** as completed

**Comment by mikkonie** [comment]
marked the task **Update timeline UI screenshot** as completed

**Comment by mikkonie** [comment]
mentioned in commit 1c7fc4e13eb4f40da854915fb6403e513f70e726

**Comment by mikkonie** [comment]
Done.
