### ISSUE TITLE
Prepare SODAR Core for public Github release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#90]
We want to do this by January.

Tasks:
* [x] #46 (a simple token check should suffice, also requires changes to sodar_taskflow)
* [x] ~~#47 postponed, see task comments~~
* [x] Cleanup code (unnecessary comments, formatting errors etc)
* [x] Update system setup scripts (Drop support < Xenial) (#103)
* [x] Read through documentation, fix obvious oversights (see #50)
* [x] Standardize docstrings for API documentation (see #50)
* [x] Configure Travis CI setup
* [x] Add note regarding issue IDs refering to our internal IDs
* [x] Update author information to CUBI
