### ISSUE TITLE
Timeline: Use modal instead of popover for event status list

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#912]
It is a well documented fact that Bootstrap popovers suck. The easiest way to do #910 and #911 is to simply switch to using a modal, as we already do everywhere else.

## Tasks

- [x] Switch from popover to modal
- [x] Update tests if necessary
- [x] Update screenshots in manual

**Comment by mikkonie** [comment]
mentioned in commit d8c1c4ffbe32a9ff21b11ab46b41224c6f7d78d9

**Comment by mikkonie** [comment]
marked the task **Switch from popover to modal** as completed

**Comment by mikkonie** [comment]
marked the task **Update tests if necessary** as completed

**Comment by mikkonie** [comment]
marked the task **Update screenshots in manual** as completed

**Comment by mikkonie** [comment]
Done.
