### ISSUE TITLE
Projectroles: Client side loading of entire project list

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#913]
Since #908 worked so well, might go one step further and load the entire list dynamically, THEN load the custom columns dynamically.

This means that while it might still take a bit of time to load a large project list (before the major changes for #825 get done), the rest of the UI will be immediately accessible. This includes site apps, search etc.

## Tasks

- [x] Query list from ajax
- [x] Display standard project info
- [x] Display extra icons
- [x] Query and display custom columns
- [x] Query and display role column
- [x] Ensure zero results are correctly displayed
- [x] Disable mouseover from zero results and loading
- [x] Ensure filtering and starring work correctly
- [x] Disable filtering and starring while loading
- [x] Update depth for parent
- [x] Move card into to `_project_list.html`
- [x] Move `data-custom-col-url` under `table` element
- [x] Move `_project_list_header.html` under `_project_list.html`
- [x] Ensure everything works under category
- [x] Update tests as necessary
- [x] Ensure proper permissions for ajax views including anon access
- [x] Add tests for new ajax views
- [x] Remove unused template tags and related tests
- [x] Remove unused projectroles templates
- [x] Cleanup new JQuery
- [x] Update screenshots in manual

**Comment by mikkonie** [comment]
mentioned in commit 9f843442e330b93428993315e263a9e20967fc76

**Comment by mikkonie** [comment]
After working halfway through this I must concede that this would be a LOT nicer to implement in Vue. Perhaps I'll upgrade this for v1.0 or somewhere beyond that.

**Comment by mikkonie** [comment]
marked the task **Disable filtering and starring while loading** as completed

**Comment by mikkonie** [comment]
marked the task **Move card into to `_project_list.html`** as completed

**Comment by mikkonie** [comment]
marked the task **Display extra icons** as completed

**Comment by mikkonie** [comment]
marked the task **Ensure zero results are correctly displayed** as completed

**Comment by mikkonie** [comment]
marked the task **Disable mouseover from zero results and loading** as completed

**Comment by mikkonie** [comment]
marked the task **Update depth for parent** as completed

**Comment by mikkonie** [comment]
mentioned in commit 1f8e915272ee8fe57797b9c96c7d74eca46bddd5

**Comment by mikkonie** [comment]
mentioned in commit 7ab116f22e0e4eb91045ca66a9d8a719d26b8879

**Comment by mikkonie** [comment]
marked the task **Query and display role column** as completed

**Comment by mikkonie** [comment]
marked the task **Move `data-custom-col-url` under `table` element** as completed

**Comment by mikkonie** [comment]
marked the task **Move `_project_list_header.html` under `_project_list.html`** as completed

**Comment by mikkonie** [comment]
marked the task **Remove unused projectroles templates** as completed

**Comment by mikkonie** [comment]
mentioned in commit 348ef9aec7f825ab4bdce86504c04abde895289b

**Comment by mikkonie** [comment]
marked the task **Remove unused template tags and related tests** as completed

**Comment by mikkonie** [comment]
mentioned in commit ca680ebff04c94bd6e9a6378c915ac150dbc60fb

**Comment by mikkonie** [comment]
marked the task **Ensure filtering and starring work correctly** as completed

**Comment by mikkonie** [comment]
marked the task **Ensure everything works under category** as completed

**Comment by mikkonie** [comment]
mentioned in commit 0acac7e8d5a296d08147bf8294b028a9d1fcda53

**Comment by mikkonie** [comment]
marked the task **Cleanup new JQuery** as completed

**Comment by mikkonie** [comment]
mentioned in commit f4fabe4fc47aa3c88b75b46cd45a3b0af3ca8577

**Comment by mikkonie** [comment]
mentioned in commit 50f8186bc29299eb4b78456cbb074af49c1ea65e

**Comment by mikkonie** [comment]
marked the task **Update tests as necessary** as completed

**Comment by mikkonie** [comment]
marked the task **Ensure proper permissions for ajax views including anon access** as completed

**Comment by mikkonie** [comment]
mentioned in commit a9ced9827f02eb30130c1c01d1334dab7322f149

**Comment by mikkonie** [comment]
marked the task **Add tests for new ajax views** as completed

**Comment by mikkonie** [comment]
mentioned in commit d33658c08e07c266beed32705bccaef7413c2688

**Comment by mikkonie** [comment]
mentioned in commit 1512dd07cf01ef3518d0471a37a8f2c94f5a7324

**Comment by mikkonie** [comment]
marked the task **Update screenshots in manual** as completed

**Comment by mikkonie** [comment]
Done.
