### ISSUE TITLE
Enable user to leave a project

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#918]
This is a feature which has been discussed for a long time, but never been prioritized. Recently, I've had multiple requests from SODAR users to remove their roles from projects, as the owners and delegates are seemingly too busy to do so. Might as well go ahead with this.

Requires #638 and #1011.

## Spec

- Add "leave project" UI button next to "Member Operations" dropdown
    * Display button IF request user has non-overridden local role in project AND role != owner
        + Hint: `if project.get_role(user=request.user).project == project` means non-overridden local role
    * Display project/category legend in button using `get_display_name()`
    * Use `danger` color on button
    * **TBD:** If inherited role, replace with button directing to category with local role?
- Link should direct to project leaving confirmation view
    * Create new view, use existing role modify helpers
    * View should be accessible to anyone with local role
- Display alerts on confirmation page
    * Alert for leaving the category/project and not being able to rejoin unless access given by owner/delegate
    * List roles in child projects/categories and warn about also losing access to them
- Once confirmed, in POST request:
    * Delete local role
    * Call ModifyPluginAPI for role removal
    * Add AppAlert and send email to owners and delegates of project/category about user leaving
        + **TBD:** Also raise these for owners and delegates of child projects, if applicable?

## Tasks

- [x] Add basic confirmation view and template
- [x] Add permission tests for view
- [x] Add link in rule view
- [x] Add logic and UI tests for link
- [x] Add logic for deletion in view
- [x] Add view tests
- [x] Update documentation

**Comment by mikkonie** [comment]
Done.
