### ISSUE TITLE
Projectroles: Generate full title of project as a model field and refactor usage

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#93]
When we want to get the full title of the project including parent category names, having to call `get_full_title()` and filtering project results manually is verbose, ugly and most likely inefficient when scaling up. It would be much better to have this as a model field to be able to use it in Django queries directly.

## Plan

- Create a `full_title` char field in the `Project` model
- Add generation of the `full_title` field value in `Project.save()`
- In the migration script created for the change, add code to populate values in existing objects in the model
- Handle full name updating for all child categories/projects of a category when:
    * Category is renamed
    * OR category is moved under another category      
    * ..so basically, make sure just to call `save()` for all of them
- Keep the existing `get_full_title()` helper for now
    * Add logging to `projectroles.models`
    * Log warning about this function being deprecated whenever it's called
    * We'll remove the helper in v0.11
- Refactor usage of `get_full_title()` wherever it appears in SODAR Core
- Add/update tests
- Update docs
    * Add a deprecation notice about `get_full_title()` into Major Changes / Breaking Changes

## Tasks

- [x] Create `full_title` field in `Project` model
- [x] Add generation of the field value in `Project.save()`
- [x] Add populating existing fields into the generated database migration
- [x] Handle child title updates for category modifications
- [x] Test child full_title renaming on category rename
- [x] Test child full_title renaming on category move
- [x] Add depraction warning logging to `get_full_title()`
- [ ] Replace usage of `get_full_title()` everywhere in SODAR Core
- [x] Update tests
- [x] Update docs
